## pandas

판다스는 전처리, 통계분석을 해준다.

전처리와 통계치(그래프로 분석하는 것 포함)를 뽑아내는것(EDA)하는 데 쓰인다.

먼저 데이터를 불러 들이는 것... 
판다스는 R 의 기능을 많이 지원해준다

In [1]:
import pandas as pd #보통 pd 2글자로 줄여서 쓴다.

In [2]:
pd.__version__

'0.23.0'

In [3]:
!python -m pip install --upgrade pip

Collecting pip
  Downloading https://files.pythonhosted.org/packages/5f/25/e52d3f31441505a5f3af41213346e5b6c221c9e086a166f3703d2ddaf940/pip-18.0-py2.py3-none-any.whl (1.3MB)
Installing collected packages: pip
  Found existing installation: pip 10.0.1
    Uninstalling pip-10.0.1:
      Successfully uninstalled pip-10.0.1
Successfully installed pip-18.0

In [5]:
df = pd.read_csv('data-netflix.csv') #read계열은 data frame을 돌려준다.
df.head()

,title,rating,ratingLevel,ratingDescription,release year,user rating score,user rating size
0,White Chicks,PG-13,"crude and sexual humor, language and some drug...",80,2004,82.0,80
1,Lucky Number Slevin,R,"strong violence, sexual content and adult lang...",100,2006,NaN,82
2,Grey's Anatomy,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,98.0,80
3,Prison Break,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2008,98.0,80
4,How I Met Your Mother,TV-PG,Parental guidance suggested. May not be suitab...,70,2014,94.0,80

In [6]:
type(df) #DataFrame 클래스 -> Pascal 방식으로 표현됨

pandas.core.frame.DataFrame

In [7]:
dir(df)

['T',
 '_AXIS_ALIASES',
 '_AXIS_IALIASES',
 '_AXIS_LEN',
 '_AXIS_NAMES',
 '_AXIS_NUMBERS',
 '_AXIS_ORDERS',
 '_AXIS_REVERSED',
 '_AXIS_SLICEMAP',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_wrap__',
 '__bool__',
 '__bytes__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__div__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdiv__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__unicode__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_add_numeric_operations',
 '_add_series_only_operations',
 '_add_series_or_dataframe_operations',
 '_agg_by_level',
 '_agg_doc',
 '_aggregate',
 '_aggregate_multiple_funcs',
 '_align_frame',
 '_align_series',
 '_box_col_values',
 '_box_item_values',
 '_builtin_table',
 '_check_inplace_setting',
 '_check_is_chained_assignment_possible',
 '_check_label_or_level_ambiguity',
 '_check_percentile',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_combine_const',
 '_combine_frame',
 '_combine_match_columns',
 '_combine_match_index',
 '_compare_frame',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_axes_dict_for_slice',
 '_construct_axes_dict_from',
 '_construct_axes_from_arguments',
 '_constructor',
 '_constructor_expanddim',
 '_constructor_sliced',
 '_convert',
 '_count_level',
 '_create_indexer',
 '_cython_table',
 '_deprecations',
 '_dir_additions',
 '_dir_deletions',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_ensure_valid_index',
 '_expand_axes',
 '_find_valid_index',
 '_from_arrays',
 '_from_axes',
 '_get_agg_axis',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cacher',
 '_get_index_resolvers',
 '_get_item_cache',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_get_values',
 '_getitem_array',
 '_getitem_column',
 '_getitem_frame',
 '_getitem_multilevel',
 '_getitem_slice',
 '_gotitem',
 '_iget_item_cache',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_info_repr',
 '_init_dict',
 '_init_mgr',
 '_init_ndarray',
 '_internal_names',
 '_internal_names_set',
 '_is_builtin_func',
 '_is_cached',
 '_is_copy',
 '_is_cython_func',
 '_is_datelike_mixed_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_is_numeric_mixed_type',
 '_is_view',
 '_ix',
 '_ixs',
 '_join_compat',
 '_maybe_cache_changed',
 '_maybe_update_cacher',
 '_metadata',
 '_needs_reindex_multi',
 '_obj_with_exclusions',
 '_protect_consolidate',
 '_reduce',
 '_reindex_axes',
 '_reindex_axis',
 '_reindex_columns',
 '_reindex_index',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_repr_data_resource_',
 '_repr_fits_horizontal_',
 '_repr_fits_vertical_',
 '_repr_html_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_sanitize_column',
 '_selected_obj',
 '_selection',
 '_selection_list',
 '_selection_name',
 '_series',
 '_set_as_cached',
 '_set_axis',
 '_set_axis_name',
 '_set_is_copy',
 '_set_item',
 '_set_value',
 '_setitem_array',
 '_setitem_frame',
 '_setitem_slice',
 '_setup_axes',
 '_shallow_copy',
 '_slice',
 '_stat_axis',
 '_stat_axis_name',
 '_stat_axis_number',
 '_take',
 '_to_dict_of_blocks',
 '_try_aggregate_string_function',
 '_typ',
 '_unpickle_frame_compat',
 '_unpickle_matrix_compat',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 '_xs',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'append',
 'apply',
 'applymap',
 'as_matrix',
 'asfreq',
 'asof',
 'assign',
 'astype',
 'at',
 'at_time',
 'axes',
 'between_time',
 'bfill',
 'bool',
 'boxplot',
 'clip',
 'clip_lower',
 'clip_upper',
 'columns',
 'combine',
 'combine_first',
 'compound',
 'copy',
 'corr',
 'corrwith',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'dot',
 'drop',
 'drop_duplicates',
 'dropna',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'eval',
 'ewm',
 'expanding',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'floordiv',
 'from_dict',
 'from_records',
 'ftypes',
 'ge',
 'get',
 'get_dtype_counts',
 'get_ftype_counts',
 'get_values',
 'groupby',
 'gt',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'insert',
 'interpolate',
 'isin',
 'isna',
 'isnull',
 'items',
 'iteritems',
 'iterrows',
 'itertuples',
 'ix',
 'join',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'loc',
 'lookup',
 'lt',
 'mad',
 'mask',
 'max',
 'mean',
 'median',
 'melt',
 'memory_usage',
 'merge',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pct_change',
 'pipe',
 'pivot',
 'pivot_table',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'query',
 'radd',
 'rank',
 'rating',
 'ratingDescription',
 'ratingLevel',
 'rdiv',
 'reindex',
 'reindex_axis',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'select',
 'select_dtypes',
 'sem',
 'set_axis',
 'set_index',
 'shape',
 'shift',
 'size',
 'skew',
 'slice_shift',
 'sort_index',
 'sort_values',
 'squeeze',
 'stack',
 'std',
 'style',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'title',
 'to_clipboard',
 'to_csv',
 'to_dense',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_gbq',
 'to_hdf',
 'to_html',
 'to_json',
 'to_latex',
 'to_msgpack',
 'to_panel',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sparse',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tshift',
 'tz_convert',
 'tz_localize',
 'unstack',
 'update',
 'values',
 'var',
 'where',
 'xs']

In [8]:
df.info() # 데이터는 1000개짜리. column은 7개. 
# non-null -> 데이터 누락 X. 
# 데이터 타입은 크게 숫자형.문자형.

# 근데 ratingLevel은 941개, user rating score는 605개 있다. non-null인데 왜 1000개가 아니지?
# object는 string데이터를 나타낼 때가 많다.
# memory usage -> pandas는 모든 데이터를 메모리에 올려서 사용한다.
# 그래서 속도가 빠르다. 하지만 메모리보다 큰 범위를 해결할 수가 없다.
# dask는 디스크 기반으로 pandas처럼 할 수 있다. -> 그러나 디스크 기반이므로 속도가 느림.
# Excel에서 하는걸 거의 대부분 pandas에서 한다.
# 몇백만개는 우습게 할 것이다

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
title                1000 non-null object
rating               1000 non-null object
ratingLevel          941 non-null object
ratingDescription    1000 non-null int64
release year         1000 non-null int64
user rating score    605 non-null float64
user rating size     1000 non-null int64
dtypes: float64(1), int64(3), object(3)
memory usage: 54.8+ KB

In [9]:
df.describe() # 기본적인 통계값을 준다. -> 우리 column이 7개 였는데 4개만 보여주네???
# --> 숫자형 데이터들을 보여준다!!!! R에서의 summary와 비슷함.

       ratingDescription  release year  user rating score  user rating size
count         1000.00000   1000.000000         605.000000       1000.000000
mean            67.36600   2010.335000          84.094215         80.783000
std             30.78561      8.877927          12.344371          0.973066
min             10.00000   1940.000000          55.000000         80.000000
25%             35.00000   2007.000000          75.000000         80.000000
50%             60.00000   2015.000000          88.000000         80.000000
75%             90.00000   2016.000000          95.000000         82.000000
max            124.00000   2017.000000          99.000000         82.000000

표준편차가 크다 : 의견이 다양하다,

info , describe

In [15]:
type(df.head())

pandas.core.frame.DataFrame

df.head() 의 데이터 타입이 데이터프레임

In [14]:
df.head().info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
title                5 non-null object
rating               5 non-null object
ratingLevel          5 non-null object
ratingDescription    5 non-null int64
release year         5 non-null int64
user rating score    4 non-null float64
user rating size     5 non-null int64
dtypes: float64(1), int64(3), object(3)
memory usage: 360.0+ bytes

head 와 tail 은 큰 의미를 가진다
앞과 뒤의 분포가 다른걸 가질확률이 크다.

In [16]:
df.head().describe()

       ratingDescription  release year  user rating score  user rating size
count           5.000000      5.000000           4.000000          5.000000
mean           86.000000   2009.600000          93.000000         80.400000
std            11.401754      5.176872           7.571878          0.894427
min            70.000000   2004.000000          82.000000         80.000000
25%            80.000000   2006.000000          91.000000         80.000000
50%            90.000000   2008.000000          96.000000         80.000000
75%            90.000000   2014.000000          98.000000         80.000000
max           100.000000   2016.000000          98.000000         82.000000

In [17]:
df.tail().describe()

       ratingDescription  release year  user rating score  user rating size
count           5.000000      5.000000           2.000000               5.0
mean           45.000000   2012.800000          88.500000              81.0
std            13.693064      5.630275          12.020815               1.0
min            35.000000   2003.000000          80.000000              80.0
25%            35.000000   2013.000000          84.250000              80.0
50%            35.000000   2016.000000          88.500000              81.0
75%            60.000000   2016.000000          92.750000              82.0
max            60.000000   2016.000000          97.000000              82.0

mean 이  86 - > 45

판다스는 ,통계와 전처리 부분

outlier detection 이상한거 찾기

## 잘불러됬는가보고 , 전체 , 인포 ( 메모리값 ), 헤드 ,테일 ,샘플 본다  이 순서대로 간다
샘플은 랜덤하게 보는거

In [19]:
df.sample(10)

,title,rating,ratingLevel,ratingDescription,release year,user rating score,user rating size
103,The Office (U.S.),TV-14,Parents strongly cautioned. May be unsuitable ...,90,2012,97.0,80
139,Hot Girls Wanted: Turned On,TV-MA,NaN,110,2017,NaN,82
335,Trouble with the Curve,PG-13,Parents strongly cautioned. May be inappropria...,80,2012,63.0,80
659,Mulan 2,G,General Audiences. Suitable for all ages.,35,2004,85.0,80
164,Unbreakable Kimmy Schmidt,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,NaN,82
805,FernGully: The Last Rainforest,G,General Audiences. Suitable for all ages.,35,1992,70.0,80
605,Lilo & Stitch,PG,mild sci-fi action,60,2002,95.0,80
197,Only for One Night,TV-MA,NaN,110,2016,78.0,80
694,Open Season: Scared Silly,PG,rude humor and some action,60,2015,72.0,80
349,Cheer Squad,TV-PG,NaN,70,2016,61.0,80

In [40]:
wdf = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data',header=None)
#header 에 None 하면 , 컬럼명이 인덱스로됨

In [35]:
#web에 있는 데이터를 가져올 수 있다. UCI Iris data csv = , , , 쉼표로 나옴
#한달이면 툴은 배우는데 원리를 모른다, 통계라서

In [36]:
wdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
0    150 non-null float64
1    150 non-null float64
2    150 non-null float64
3    150 non-null float64
4    150 non-null object
dtypes: float64(4), object(1)
memory usage: 5.9+ KB

In [37]:
wdf.head()

     0    1    2    3            4
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa

In [38]:
wdf.tail()

       0    1    2    3               4
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

In [39]:
wdf.head().describe()

              0         1         2    3
count  5.000000  5.000000  5.000000  5.0
mean   4.860000  3.280000  1.400000  0.2
std    0.207364  0.258844  0.070711  0.0
min    4.600000  3.000000  1.300000  0.2
25%    4.700000  3.100000  1.400000  0.2
50%    4.900000  3.200000  1.400000  0.2
75%    5.000000  3.500000  1.400000  0.2
max    5.100000  3.600000  1.500000  0.2

In [30]:
wdf.tail().describe()

            5.1       3.5       1.4       0.2
count  5.000000  5.000000  5.000000  5.000000
mean   6.320000  2.980000  5.180000  2.060000
std    0.303315  0.319374  0.148324  0.230217
min    5.900000  2.500000  5.000000  1.800000
25%    6.200000  3.000000  5.100000  1.900000
50%    6.300000  3.000000  5.200000  2.000000
75%    6.500000  3.000000  5.200000  2.300000
max    6.700000  3.400000  5.400000  2.300000

In [31]:
wdf.describe()

              5.1         3.5         1.4         0.2
count  149.000000  149.000000  149.000000  149.000000
mean     5.848322    3.051007    3.774497    1.205369
std      0.828594    0.433499    1.759651    0.761292
min      4.300000    2.000000    1.000000    0.100000
25%      5.100000    2.800000    1.600000    0.300000
50%      5.800000    3.000000    4.400000    1.300000
75%      6.400000    3.300000    5.100000    1.800000
max      7.900000    4.400000    6.900000    2.500000

row 는 관측지 , column 은 변수 (구분되는것 ) - > 그래서 2차원의 형태로만든다.

분석은 2차원데이터

평균과 표준편차만 알면된다, 
많은데이터는 대부분 정규분포를 이룬다.

평균에 밀집되면 표준편차가 작아진다
평균에 멀어지면 표준편차가커진다.
스쿠니스, 

표준편차가 크고 작고,

분석은 쪼개진것을 2차원의 형태로 만들어야한다.  나눠진 테이블을 묶어야함.
DB에서는 붙어있는것을 쪼개어 나누었다, 그것의 반대이다.

In [41]:
wdf

       0    1    2    3               4
0    5.1  3.5  1.4  0.2     Iris-setosa
1    4.9  3.0  1.4  0.2     Iris-setosa
2    4.7  3.2  1.3  0.2     Iris-setosa
3    4.6  3.1  1.5  0.2     Iris-setosa
4    5.0  3.6  1.4  0.2     Iris-setosa
5    5.4  3.9  1.7  0.4     Iris-setosa
6    4.6  3.4  1.4  0.3     Iris-setosa
7    5.0  3.4  1.5  0.2     Iris-setosa
8    4.4  2.9  1.4  0.2     Iris-setosa
9    4.9  3.1  1.5  0.1     Iris-setosa
10   5.4  3.7  1.5  0.2     Iris-setosa
11   4.8  3.4  1.6  0.2     Iris-setosa
12   4.8  3.0  1.4  0.1     Iris-setosa
13   4.3  3.0  1.1  0.1     Iris-setosa
14   5.8  4.0  1.2  0.2     Iris-setosa
15   5.7  4.4  1.5  0.4     Iris-setosa
16   5.4  3.9  1.3  0.4     Iris-setosa
17   5.1  3.5  1.4  0.3     Iris-setosa
18   5.7  3.8  1.7  0.3     Iris-setosa
19   5.1  3.8  1.5  0.3     Iris-setosa
20   5.4  3.4  1.7  0.2     Iris-setosa
21   5.1  3.7  1.5  0.4     Iris-setosa
22   4.6  3.6  1.0  0.2     Iris-setosa
23   5.1  3.3  1.7  0.5     Iris-setosa
24   4.8  3.4  1.9  0.2     Iris-setosa
25   5.0  3.0  1.6  0.2     Iris-setosa
26   5.0  3.4  1.6  0.4     Iris-setosa
27   5.2  3.5  1.5  0.2     Iris-setosa
28   5.2  3.4  1.4  0.2     Iris-setosa
29   4.7  3.2  1.6  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
120  6.9  3.2  5.7  2.3  Iris-virginica
121  5.6  2.8  4.9  2.0  Iris-virginica
122  7.7  2.8  6.7  2.0  Iris-virginica
123  6.3  2.7  4.9  1.8  Iris-virginica
124  6.7  3.3  5.7  2.1  Iris-virginica
125  7.2  3.2  6.0  1.8  Iris-virginica
126  6.2  2.8  4.8  1.8  Iris-virginica
127  6.1  3.0  4.9  1.8  Iris-virginica
128  6.4  2.8  5.6  2.1  Iris-virginica
129  7.2  3.0  5.8  1.6  Iris-virginica
130  7.4  2.8  6.1  1.9  Iris-virginica
131  7.9  3.8  6.4  2.0  Iris-virginica
132  6.4  2.8  5.6  2.2  Iris-virginica
133  6.3  2.8  5.1  1.5  Iris-virginica
134  6.1  2.6  5.6  1.4  Iris-virginica
135  7.7  3.0  6.1  2.3  Iris-virginica
136  6.3  3.4  5.6  2.4  Iris-virginica
137  6.4  3.1  5.5  1.8  Iris-virginica
138  6.0  3.0  4.8  1.8  Iris-virginica
139  6.9  3.1  5.4  2.1  Iris-virginica
140  6.7  3.1  5.6  2.4  Iris-virginica
141  6.9  3.1  5.1  2.3  Iris-virginica
142  5.8  2.7  5.1  1.9  Iris-virginica
143  6.8  3.2  5.9  2.3  Iris-virginica
144  6.7  3.3  5.7  2.5  Iris-virginica
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

[150 rows x 5 columns]

데이터 새로 한줄은 시리즈 , 왼쪽 번호는 인덱스 , 위에 컬럼명, 혹은  인덱스,

(리스트, 튜플 , 이런것들은 ) dataframe 도 시퀀스는 인덱싱과 슬라이싱이 된다.

In [58]:
df = pd.read_csv('data-netflix.csv',header=2)
df

,Lucky Number Slevin,R,"strong violence, sexual content and adult language",100,2006,NA,82
0,Grey's Anatomy,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,98.0,80
1,Prison Break,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2008,98.0,80
2,How I Met Your Mother,TV-PG,Parental guidance suggested. May not be suitab...,70,2014,94.0,80
3,Supernatural,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,95.0,80
4,Breaking Bad,TV-MA,For mature audiences. May not be suitable for...,110,2013,97.0,80
5,The Vampire Diaries,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2017,91.0,80
6,The Walking Dead,TV-MA,For mature audiences. May not be suitable for...,110,2015,98.0,80
7,Pretty Little Liars,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,96.0,80
8,Once Upon a Time,TV-PG,Parental guidance suggested. May not be suitab...,70,2016,98.0,80
9,Sherlock,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,95.0,80
10,Death Note,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2006,77.0,80
11,Naruto,TV-PG,Parental guidance suggested. May not be suitab...,70,2008,88.0,80
12,The Hunter,R,language and brief violence,100,2011,NaN,82
13,Lottie Dottie Chicken,TV-Y,Suitable for all ages.,10,2009,NaN,82
14,Arrow,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2015,96.0,80
15,Black Mirror,TV-MA,For mature audiences. May not be suitable for...,110,2016,80.0,80
16,The Originals,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,74.0,80
17,The 100,NR,This movie has not been rated.,124,2016,97.0,80
18,Masha and the Bear,TV-Y,Suitable for all ages.,10,2013,81.0,80
19,"Ã“ Pai, Ã“ - Look at This",TV-MA,For mature audiences. May not be suitable for...,110,2007,NaN,82
20,Nymphomaniac: Volume 1,NR,This movie has not been rated.,124,2013,NaN,82
21,Hunter X Hunter (2011),NR,This movie has not been rated.,124,2013,57.0,80
22,Marvel's Luke Cage,TV-MA,For mature audiences. May not be suitable for...,110,2016,95.0,80
23,Marvel's Iron Fist,TV-MA,NaN,110,2017,98.0,80
24,Narcos,TV-MA,For mature audiences. May not be suitable for...,110,2016,94.0,80
25,The Flash,TV-PG,Parental guidance suggested. May not be suitab...,70,2016,98.0,80
26,The Seven Deadly Sins,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,NaN,82
27,Scream,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,NaN,82
28,The Do-Over,TV-MA,For mature audiences. May not be suitable for...,110,2016,84.0,80
29,OperaÃ§Ãµes Especiais,TV-MA,NaN,110,2015,NaN,82
...,...,...,...,...,...,...,...
968,Annie,PG,adult content and mld violence,60,1982,68.0,80
969,An American Tail: Fievel Goes West,G,General Audiences. Suitable for all ages.,35,1991,NaN,82
970,D2: The Mighty Ducks,PG,some mild language and rough hockey action,60,1994,70.0,80
971,"Honey, I Shrunk the Kids",PG,Parental guidance suggested. May not be suitab...,60,1989,80.0,80
972,The Iron Giant,PG,fantasy action and mild language,60,1999,83.0,80
973,The Fox and the Hound 2,G,General Audiences. Suitable for all ages.,35,2006,NaN,82
974,Air Buddies,PG,"some mild, rude humor",60,2006,NaN,82
975,Dr. Dolittle: Tail to the Chief,PG,brief mild language and some rude behavior,60,2008,NaN,82
976,Flicka 2,PG,some reckless behavior,60,2010,NaN,82
977,H2O: Just Add Water,TV-PG,Parental guidance suggested. May not be suitab...,70,2009,74.0,80
978,The Gruffalo,TV-Y,Suitable for all ages.,10,2009,NaN,82
979,Dolphin Tale,PG,some mild thematic elements,60,2011,NaN,82
980,Pound Puppies,TV-Y,Suitable for all ages.,10,2013,NaN,82
981,Beverly Hills Chihuahua 3: Viva La Fiesta!,G,General Audiences. Suitable for all ages.,35,2012,NaN,82
982,The Magic School Bus,TV-Y,Suitable for all ages.,10,1997,81.0,80
983,Step Dogs,TV-PG,Parental guidance suggested. May not be suitab...,70,2013,NaN,82
984,PokÃ©mon: Indigo League,TV-Y,Suitable for all ages.,10,2000,74.0,80
985,Mia and Me,TV-Y,Suitable for all ages.,10,2015,NaN,82
986,Paddington,PG,mild action and rude humor,60,2014,70.0,80
987,Russell Madness,PG,some rude humor and sports action,60,2015,NaN,82
988,My Animal Friends,TV-Y,Suitable for all ages.,10,2013,NaN,82
989,Dawn of the Croods,TV-Y7,Suitable for children ages 7 and older,41,2017,72.0,80
990,Alpha and Omega: Dino Digs,TV-G,Suitable for all ages.,35,2016,NaN,82
991,Wiener Dog Internationals,G,General Audiences. Suitable for all ages.,35,2015,NaN,82
992,Pup Star,G,General Audiences. Suitable for all ages.,35,2016,NaN,82
993,The BFG,PG,"for action/peril, some scary moments and brief...",60,2016,97.0,80
994,The Secret Life of Pets,PG,for action and some rude humor,60,2016,NaN,81
995,Precious Puppies,TV-G,Suitable for all ages.,35,2003,NaN,82
996,Beary Tales,TV-G,Suitable for all ages.,35,2013,NaN,82
997,Growing Up Wild,G,NaN,35,2016,80.0,80

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 998 entries, 0 to 997
Data columns (total 7 columns):
Lucky Number Slevin                                   998 non-null object
R                                                     998 non-null object
strong violence, sexual content and adult language    939 non-null object
100                                                   998 non-null int64
2006                                                  998 non-null int64
NA                                                    604 non-null float64
82                                                    998 non-null int64
dtypes: float64(1), int64(3), object(3)
memory usage: 54.7+ KB

header 2를 하니까 데이터를 날려버림

In [65]:
#인덱스 컬럼을 잡아줄 수 있다. 인덱스는 해쉬와 같다. 

df = pd.read_csv('data-netflix.csv',usecols = ['title','rating','release year'])
df

                                          title rating  release year
0                                  White Chicks  PG-13          2004
1                           Lucky Number Slevin      R          2006
2                                Grey's Anatomy  TV-14          2016
3                                  Prison Break  TV-14          2008
4                         How I Met Your Mother  TV-PG          2014
5                                  Supernatural  TV-14          2016
6                                  Breaking Bad  TV-MA          2013
7                           The Vampire Diaries  TV-14          2017
8                              The Walking Dead  TV-MA          2015
9                           Pretty Little Liars  TV-14          2016
10                             Once Upon a Time  TV-PG          2016
11                                     Sherlock  TV-14          2016
12                                   Death Note  TV-14          2006
13                                       Naruto  TV-PG          2008
14                                   The Hunter      R          2011
15                        Lottie Dottie Chicken   TV-Y          2009
16                                        Arrow  TV-14          2015
17                                 Black Mirror  TV-MA          2016
18                                The Originals  TV-14          2016
19                                      The 100     NR          2016
20                           Masha and the Bear   TV-Y          2013
21                    Ã“ Pai, Ã“ - Look at This  TV-MA          2007
22                       Nymphomaniac: Volume 1     NR          2013
23                       Hunter X Hunter (2011)     NR          2013
24                           Marvel's Luke Cage  TV-MA          2016
25                           Marvel's Iron Fist  TV-MA          2017
26                                       Narcos  TV-MA          2016
27                                    The Flash  TV-PG          2016
28                        The Seven Deadly Sins  TV-14          2016
29                                       Scream  TV-14          2016
..                                          ...    ...           ...
970                                       Annie     PG          1982
971          An American Tail: Fievel Goes West      G          1991
972                        D2: The Mighty Ducks     PG          1994
973                    Honey, I Shrunk the Kids     PG          1989
974                              The Iron Giant     PG          1999
975                     The Fox and the Hound 2      G          2006
976                                 Air Buddies     PG          2006
977             Dr. Dolittle: Tail to the Chief     PG          2008
978                                    Flicka 2     PG          2010
979                         H2O: Just Add Water  TV-PG          2009
980                                The Gruffalo   TV-Y          2009
981                                Dolphin Tale     PG          2011
982                               Pound Puppies   TV-Y          2013
983  Beverly Hills Chihuahua 3: Viva La Fiesta!      G          2012
984                        The Magic School Bus   TV-Y          1997
985                                   Step Dogs  TV-PG          2013
986                     PokÃ©mon: Indigo League   TV-Y          2000
987                                  Mia and Me   TV-Y          2015
988                                  Paddington     PG          2014
989                             Russell Madness     PG          2015
990                           My Animal Friends   TV-Y          2013
991                          Dawn of the Croods  TV-Y7          2017
992                  Alpha and Omega: Dino Digs   TV-G          2016
993                   Wiener Dog Internationals      G          2015
994                                    Pup Star      G          2016
995                                     The BFG     PG          2016
996                     The Secret Life of Pets     PG          2016
997                            Precious Puppies   TV-G          2003
998                                 Beary Tales   TV-G          2013
999                             Growing Up Wild      G          2016

[1000 rows x 3 columns]

보통 여러개 넣을때는 리스트로 넣는다, 
한개넣을때는 스트링으로 넣는다.
list 특징 :  <뮤터블 시퀀스 컨테이너>

똑똑한사람들은 처음부터 몇몇 컬럼이 필요없다고 뺀다 . 메모리에 다 올리는거라서

Ad hoc  : 특정문제는 특정 답만있다, 일반해는없다  no free lunch 공짜밥은없다 , 어떠한것을 하기위해서는 어떤노력을해야한다, 돌려말하면 일반적인 해답이 없다. 모든 경우에 맞는 답은없다

In [ ]:
df = pd.read_csv('data-netflix.csv',na_values=[""])  # 널값을 지정해줄수있다.

In [ ]:
df =pd.read_csv('data-netflix.csv',skip_blank_lines=False)

## Skip rows

In [66]:
df.tail(2)

               title rating  release year
998      Beary Tales   TV-G          2013
999  Growing Up Wild      G          2016

In [67]:
df =pd.read_csv('data-netflix.csv',skipfooter=2,engine='python')  #뭐 안된다 깨진다, 인코딩에러 시 engine 에 파이썬 쓴다.

In [68]:
df.tail(2)

,title,rating,ratingLevel,ratingDescription,release year,user rating score,user rating size
996,The Secret Life of Pets,PG,for action and some rude humor,60,2016,NaN,81
997,Precious Puppies,TV-G,Suitable for all ages.,35,2003,NaN,82

C 에 비해서 파이썬은 5배에서 100 배 가 느리다. 깨질때 engine (Unicode) 또는 encoding 쓴다.

In [69]:
import seaborn as sns #판다스 기반의 visualize

In [71]:
data = sns.load_dataset('tips',engine="python")

In [72]:
type(data)

pandas.core.frame.DataFrame

In [74]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
total_bill    244 non-null float64
tip           244 non-null float64
sex           244 non-null category
smoker        244 non-null category
day           244 non-null category
time          244 non-null category
size          244 non-null int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.2 KB

In [75]:
data.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [76]:
data.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [77]:
data.tail()

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [78]:
df =pd.read_csv('data-netflix.csv',nrows=100)

In [79]:
df

,title,rating,ratingLevel,ratingDescription,release year,user rating score,user rating size
0,White Chicks,PG-13,"crude and sexual humor, language and some drug...",80,2004,82.0,80
1,Lucky Number Slevin,R,"strong violence, sexual content and adult lang...",100,2006,NaN,82
2,Grey's Anatomy,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,98.0,80
3,Prison Break,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2008,98.0,80
4,How I Met Your Mother,TV-PG,Parental guidance suggested. May not be suitab...,70,2014,94.0,80
5,Supernatural,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,95.0,80
6,Breaking Bad,TV-MA,For mature audiences. May not be suitable for...,110,2013,97.0,80
7,The Vampire Diaries,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2017,91.0,80
8,The Walking Dead,TV-MA,For mature audiences. May not be suitable for...,110,2015,98.0,80
9,Pretty Little Liars,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,96.0,80
10,Once Upon a Time,TV-PG,Parental guidance suggested. May not be suitab...,70,2016,98.0,80
11,Sherlock,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,95.0,80
12,Death Note,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2006,77.0,80
13,Naruto,TV-PG,Parental guidance suggested. May not be suitab...,70,2008,88.0,80
14,The Hunter,R,language and brief violence,100,2011,NaN,82
15,Lottie Dottie Chicken,TV-Y,Suitable for all ages.,10,2009,NaN,82
16,Arrow,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2015,96.0,80
17,Black Mirror,TV-MA,For mature audiences. May not be suitable for...,110,2016,80.0,80
18,The Originals,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,74.0,80
19,The 100,NR,This movie has not been rated.,124,2016,97.0,80
20,Masha and the Bear,TV-Y,Suitable for all ages.,10,2013,81.0,80
21,"Ã“ Pai, Ã“ - Look at This",TV-MA,For mature audiences. May not be suitable for...,110,2007,NaN,82
22,Nymphomaniac: Volume 1,NR,This movie has not been rated.,124,2013,NaN,82
23,Hunter X Hunter (2011),NR,This movie has not been rated.,124,2013,57.0,80
24,Marvel's Luke Cage,TV-MA,For mature audiences. May not be suitable for...,110,2016,95.0,80
25,Marvel's Iron Fist,TV-MA,NaN,110,2017,98.0,80
26,Narcos,TV-MA,For mature audiences. May not be suitable for...,110,2016,94.0,80
27,The Flash,TV-PG,Parental guidance suggested. May not be suitab...,70,2016,98.0,80
28,The Seven Deadly Sins,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,NaN,82
29,Scream,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,NaN,82
...,...,...,...,...,...,...,...
70,New Girl,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,91.0,80
71,American Horror Story,TV-MA,For mature audiences. May not be suitable for...,110,2016,90.0,80
72,Orange Is the New Black,TV-MA,For mature audiences. May not be suitable for...,110,2016,98.0,80
73,Inside Russia's Toughest Prison,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2011,NaN,82
74,Black Mirror,TV-MA,For mature audiences. May not be suitable for...,110,2016,80.0,80
75,Bates Motel,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,83.0,80
76,The 100,NR,This movie has not been rated.,124,2016,97.0,80
77,Marvel's Iron Fist,TV-MA,NaN,110,2017,98.0,80
78,Grace and Frankie,TV-MA,For mature audiences. May not be suitable for...,110,2017,90.0,80
79,How to Get Away with Murder,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,95.0,80
80,The Get Down,TV-MA,For mature audiences. May not be suitable for...,110,2017,80.0,80
81,Love,TV-MA,For mature audiences. May not be suitable for...,110,2017,NaN,82
82,The Flash,TV-PG,Parental guidance suggested. May not be suitab...,70,2016,98.0,80
83,The OA,TV-MA,For mature audiences. May not be suitable for...,110,2016,NaN,82
84,Stranger Things,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,90.0,80
85,Ingobernable,TV-MA,NaN,110,2017,96.0,80
86,Zootopia,PG,"some thematic elements, rude humor and action",60,2016,97.0,80
87,Meet the Blacks,R,"pervasive language, some sexual material, viol...",100,2016,79.0,80
88,Finding Dory,PG,mild thematic elements,60,2016,98.0,80
89,Santa Clarita Diet,TV-MA,For mature audiences. May not be suitable for...,110,2017,82.0,80
90,Sausage Party,R,"strong crude sexual content, pervasive languag...",100,2016,91.0,80
91,Pete's Dragon,PG,"for action, peril and brief language",60,2016,93.0,80
92,Kevin Hart: What Now?,R,"some sexual material, and language throughout",100,2016,97.0,80
93,Girlboss,TV-MA,NaN,110,2017,94.0,80
94,The Discovery,TV-MA,NaN,110,2017,NaN,82
95,Sand Castle,TV-MA,NaN,110,2017,89.0,80
96,Sandy Wexler,TV-14,NaN,90,2017,92.0,80
97,Chewing Gum,TV-MA,For mature audiences. May not be suitable for...,110,2017,93.0,80
98,Cheer Squad,TV-PG,NaN,70,2016,61.0,80
99,Only for One Night,TV-MA,NaN,110,2016,78.0,80

In [80]:
df.shape

(100, 7)

In [81]:
# numpy 에서 shape 봄. pandas 도 numpy 기반, 파이썬은 C 보다 5-100배느린게 정설이다 . 
# numpy가 C 기반이다 . 따라서 매우 빠르다 ,

위의 shape 은 100줄 , 컬럼 7개

In [82]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
title                100 non-null object
rating               100 non-null object
ratingLevel          83 non-null object
ratingDescription    100 non-null int64
release year         100 non-null int64
user rating score    75 non-null float64
user rating size     100 non-null int64
dtypes: float64(1), int64(3), object(3)
memory usage: 5.5+ KB

In [83]:
#우리는 2차원데이터로 통일을 해야 분석을 할 수 있다.

In [85]:
movies_json = pd.read_json('data-netflix.json')

In [86]:
movies_json

,title,rating,ratingLevel,ratingDescription,release year,user rating score,user rating size
0,White Chicks,PG-13,"crude and sexual humor, language and some drug...",80,2004,82.0,80
1,Lucky Number Slevin,R,"strong violence, sexual content and adult lang...",100,2006,NaN,82
10,Once Upon a Time,TV-PG,Parental guidance suggested. May not be suitab...,70,2016,98.0,80
100,The Life Aquatic with Steve Zissou,R,"language, some drug use, violence and partial ...",100,2004,NaN,82
101,Lucky Number Slevin,R,"strong violence, sexual content and adult lang...",100,2006,NaN,82
102,The L Word,TV-MA,For mature audiences. May not be suitable for...,110,2009,NaN,82
103,The Office (U.S.),TV-14,Parents strongly cautioned. May be unsuitable ...,90,2012,97.0,80
104,30 Rock,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2012,66.0,80
105,Mad Men,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2014,75.0,80
106,It's Always Sunny in Philadelphia,TV-MA,For mature audiences. May not be suitable for...,110,2016,91.0,80
107,Californication,TV-MA,For mature audiences. May not be suitable for...,110,2014,63.0,80
108,Parks and Recreation,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2015,94.0,80
109,Friends,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2003,98.0,80
11,Sherlock,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,95.0,80
110,Shameless (U.S.),TV-MA,For mature audiences. May not be suitable for...,110,2016,97.0,80
111,Portlandia,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,62.0,80
112,New Girl,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,91.0,80
113,Don't Trust the B---- in Apartment 23,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2012,NaN,82
114,Friends with Benefits,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2011,NaN,82
115,The Client List,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2013,92.0,80
116,Halt and Catch Fire,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,NaN,82
117,5 to 7,R,some sexual material,100,2014,NaN,82
118,Marvel's Iron Fist,TV-MA,None,110,2017,98.0,80
119,Chef's Table,TV-MA,For mature audiences. May not be suitable for...,110,2017,NaN,82
12,Death Note,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2006,77.0,80
120,Documentary Now!,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,NaN,82
121,Grace and Frankie,TV-MA,For mature audiences. May not be suitable for...,110,2017,90.0,80
122,Better Call Saul,TV-MA,For mature audiences. May not be suitable for...,110,2016,95.0,80
123,The Get Down,TV-MA,For mature audiences. May not be suitable for...,110,2017,80.0,80
124,Schitt's Creek,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,74.0,80
...,...,...,...,...,...,...,...
972,D2: The Mighty Ducks,PG,some mild language and rough hockey action,60,1994,70.0,80
973,"Honey, I Shrunk the Kids",PG,Parental guidance suggested. May not be suitab...,60,1989,80.0,80
974,The Iron Giant,PG,fantasy action and mild language,60,1999,83.0,80
975,The Fox and the Hound 2,G,General Audiences. Suitable for all ages.,35,2006,NaN,82
976,Air Buddies,PG,"some mild, rude humor",60,2006,NaN,82
977,Dr. Dolittle: Tail to the Chief,PG,brief mild language and some rude behavior,60,2008,NaN,82
978,Flicka 2,PG,some reckless behavior,60,2010,NaN,82
979,H2O: Just Add Water,TV-PG,Parental guidance suggested. May not be suitab...,70,2009,74.0,80
98,Cheer Squad,TV-PG,None,70,2016,61.0,80
980,The Gruffalo,TV-Y,Suitable for all ages.,10,2009,NaN,82
981,Dolphin Tale,PG,some mild thematic elements,60,2011,NaN,82
982,Pound Puppies,TV-Y,Suitable for all ages.,10,2013,NaN,82
983,Beverly Hills Chihuahua 3: Viva La Fiesta!,G,General Audiences. Suitable for all ages.,35,2012,NaN,82
984,The Magic School Bus,TV-Y,Suitable for all ages.,10,1997,81.0,80
985,Step Dogs,TV-PG,Parental guidance suggested. May not be suitab...,70,2013,NaN,82
986,PokÃ©mon: Indigo League,TV-Y,Suitable for all ages.,10,2000,74.0,80
987,Mia and Me,TV-Y,Suitable for all ages.,10,2015,NaN,82
988,Paddington,PG,mild action and rude humor,60,2014,70.0,80
989,Russell Madness,PG,some rude humor and sports action,60,2015,NaN,82
99,Only for One Night,TV-MA,None,110,2016,78.0,80
990,My Animal Friends,TV-Y,Suitable for all ages.,10,2013,NaN,82
991,Dawn of the Croods,TV-Y7,Suitable for children ages 7 and older,41,2017,72.0,80
992,Alpha and Omega: Dino Digs,TV-G,Suitable for all ages.,35,2016,NaN,82
993,Wiener Dog Internationals,G,General Audiences. Suitable for all ages.,35,2015,NaN,82
994,Pup Star,G,General Audiences. Suitable for all ages.,35,2016,NaN,82
995,The BFG,PG,"for action/peril, some scary moments and brief...",60,2016,97.0,80
996,The Secret Life of Pets,PG,for action and some rude humor,60,2016,NaN,81
997,Precious Puppies,TV-G,Suitable for all ages.,35,2003,NaN,82
998,Beary Tales,TV-G,Suitable for all ages.,35,2013,NaN,82
999,Growing Up Wild,G,None,35,2016,80.0,80

In [87]:
df = pd.read_pickle('data-netflix.p')

In [88]:
df.head()

,title,rating,ratingLevel,ratingDescription,release year,user rating score,user rating size
0,White Chicks,PG-13,"crude and sexual humor, language and some drug...",80,2004,82.0,80
1,Lucky Number Slevin,R,"strong violence, sexual content and adult lang...",100,2006,NaN,82
2,Grey's Anatomy,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,98.0,80
3,Prison Break,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2008,98.0,80
4,How I Met Your Mother,TV-PG,Parental guidance suggested. May not be suitab...,70,2014,94.0,80

pickle 은 파이썬에서 객체를 저장하는것,직렬화 방식 ,중간저장할대 pickle 많이씀.  확장자 마음데로가능.

In [141]:
import sqlite3

In [142]:
conn= sqlite3.connect('data-netflix.sqlite')

In [143]:
df = pd.read_sql_query("SELECT * FROM data_netflix;",conn)

In [144]:
df.head()

,ogc_fid,title,rating,ratinglevel,ratingdescription,release year,user rating score,user rating size
0,1,White Chicks,PG-13,"crude and sexual humor, language and some drug...",80,2004,82,80
1,2,Lucky Number Slevin,R,"strong violence, sexual content and adult lang...",100,2006,NA,82
2,3,Grey's Anatomy,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,98,80
3,4,Prison Break,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2008,98,80
4,5,How I Met Your Mother,TV-PG,Parental guidance suggested. May not be suitab...,70,2014,94,80

sql 안쓰고 바로 orm 으로 바꾸는게 가능하다 .

객체만들고 ,인스턴스 방법. 클래스 메소드중 from 방법,

In [148]:
df = pd.read_csv('data-netflix.csv',encoding="utf-8")
df.to_html('ddd.html')

UnicodeEncodeError: 'cp949' codec can't encode character '\xc3' in position 92661: illegal multibyte sequence

In [110]:
df[["title","rating"]] #판다스는 여러개있으면 list 로 쓴다, 열을 가져올때는 이름을 쓴다

                                          title rating
0                                  White Chicks  PG-13
1                           Lucky Number Slevin      R
2                                Grey's Anatomy  TV-14
3                                  Prison Break  TV-14
4                         How I Met Your Mother  TV-PG
5                                  Supernatural  TV-14
6                                  Breaking Bad  TV-MA
7                           The Vampire Diaries  TV-14
8                              The Walking Dead  TV-MA
9                           Pretty Little Liars  TV-14
10                             Once Upon a Time  TV-PG
11                                     Sherlock  TV-14
12                                   Death Note  TV-14
13                                       Naruto  TV-PG
14                                   The Hunter      R
15                        Lottie Dottie Chicken   TV-Y
16                                        Arrow  TV-14
17                                 Black Mirror  TV-MA
18                                The Originals  TV-14
19                                      The 100     NR
20                           Masha and the Bear   TV-Y
21                    Ã“ Pai, Ã“ - Look at This  TV-MA
22                       Nymphomaniac: Volume 1     NR
23                       Hunter X Hunter (2011)     NR
24                           Marvel's Luke Cage  TV-MA
25                           Marvel's Iron Fist  TV-MA
26                                       Narcos  TV-MA
27                                    The Flash  TV-PG
28                        The Seven Deadly Sins  TV-14
29                                       Scream  TV-14
..                                          ...    ...
970                                       Annie     PG
971          An American Tail: Fievel Goes West      G
972                        D2: The Mighty Ducks     PG
973                    Honey, I Shrunk the Kids     PG
974                              The Iron Giant     PG
975                     The Fox and the Hound 2      G
976                                 Air Buddies     PG
977             Dr. Dolittle: Tail to the Chief     PG
978                                    Flicka 2     PG
979                         H2O: Just Add Water  TV-PG
980                                The Gruffalo   TV-Y
981                                Dolphin Tale     PG
982                               Pound Puppies   TV-Y
983  Beverly Hills Chihuahua 3: Viva La Fiesta!      G
984                        The Magic School Bus   TV-Y
985                                   Step Dogs  TV-PG
986                     PokÃ©mon: Indigo League   TV-Y
987                                  Mia and Me   TV-Y
988                                  Paddington     PG
989                             Russell Madness     PG
990                           My Animal Friends   TV-Y
991                          Dawn of the Croods  TV-Y7
992                  Alpha and Omega: Dino Digs   TV-G
993                   Wiener Dog Internationals      G
994                                    Pup Star      G
995                                     The BFG     PG
996                     The Secret Life of Pets     PG
997                            Precious Puppies   TV-G
998                                 Beary Tales   TV-G
999                             Growing Up Wild      G

[1000 rows x 2 columns]

In [111]:
df['title']  # 꺽쇄 하나는 시리즈 객체를 들고온다 .

0                                    White Chicks
1                             Lucky Number Slevin
2                                  Grey's Anatomy
3                                    Prison Break
4                           How I Met Your Mother
5                                    Supernatural
6                                    Breaking Bad
7                             The Vampire Diaries
8                                The Walking Dead
9                             Pretty Little Liars
10                               Once Upon a Time
11                                       Sherlock
12                                     Death Note
13                                         Naruto
14                                     The Hunter
15                          Lottie Dottie Chicken
16                                          Arrow
17                                   Black Mirror
18                                  The Originals
19                                        The 100
20                             Masha and the Bear
21                      Ã“ Pai, Ã“ - Look at This
22                         Nymphomaniac: Volume 1
23                         Hunter X Hunter (2011)
24                             Marvel's Luke Cage
25                             Marvel's Iron Fist
26                                         Narcos
27                                      The Flash
28                          The Seven Deadly Sins
29                                         Scream
                          ...
970                                         Annie
971            An American Tail: Fievel Goes West
972                          D2: The Mighty Ducks
973                      Honey, I Shrunk the Kids
974                                The Iron Giant
975                       The Fox and the Hound 2
976                                   Air Buddies
977               Dr. Dolittle: Tail to the Chief
978                                      Flicka 2
979                           H2O: Just Add Water
980                                  The Gruffalo
981                                  Dolphin Tale
982                                 Pound Puppies
983    Beverly Hills Chihuahua 3: Viva La Fiesta!
984                          The Magic School Bus
985                                     Step Dogs
986                       PokÃ©mon: Indigo League
987                                    Mia and Me
988                                    Paddington
989                               Russell Madness
990                             My Animal Friends
991                            Dawn of the Croods
992                    Alpha and Omega: Dino Digs
993                     Wiener Dog Internationals
994                                      Pup Star
995                                       The BFG
996                       The Secret Life of Pets
997                              Precious Puppies
998                                   Beary Tales
999                               Growing Up Wild
Name: title, Length: 1000, dtype: object

In [113]:
type(df['title'])

pandas.core.series.Series

In [112]:
df[['title']]  # 꺽쇄를 두개하면 데이터 프레임이됨.

                                          title
0                                  White Chicks
1                           Lucky Number Slevin
2                                Grey's Anatomy
3                                  Prison Break
4                         How I Met Your Mother
5                                  Supernatural
6                                  Breaking Bad
7                           The Vampire Diaries
8                              The Walking Dead
9                           Pretty Little Liars
10                             Once Upon a Time
11                                     Sherlock
12                                   Death Note
13                                       Naruto
14                                   The Hunter
15                        Lottie Dottie Chicken
16                                        Arrow
17                                 Black Mirror
18                                The Originals
19                                      The 100
20                           Masha and the Bear
21                    Ã“ Pai, Ã“ - Look at This
22                       Nymphomaniac: Volume 1
23                       Hunter X Hunter (2011)
24                           Marvel's Luke Cage
25                           Marvel's Iron Fist
26                                       Narcos
27                                    The Flash
28                        The Seven Deadly Sins
29                                       Scream
..                                          ...
970                                       Annie
971          An American Tail: Fievel Goes West
972                        D2: The Mighty Ducks
973                    Honey, I Shrunk the Kids
974                              The Iron Giant
975                     The Fox and the Hound 2
976                                 Air Buddies
977             Dr. Dolittle: Tail to the Chief
978                                    Flicka 2
979                         H2O: Just Add Water
980                                The Gruffalo
981                                Dolphin Tale
982                               Pound Puppies
983  Beverly Hills Chihuahua 3: Viva La Fiesta!
984                        The Magic School Bus
985                                   Step Dogs
986                     PokÃ©mon: Indigo League
987                                  Mia and Me
988                                  Paddington
989                             Russell Madness
990                           My Animal Friends
991                          Dawn of the Croods
992                  Alpha and Omega: Dino Digs
993                   Wiener Dog Internationals
994                                    Pup Star
995                                     The BFG
996                     The Secret Life of Pets
997                            Precious Puppies
998                                 Beary Tales
999                             Growing Up Wild

[1000 rows x 1 columns]

In [114]:
type(df[['title']])

pandas.core.frame.DataFrame

---

In [151]:
df = pd.read_json('data-netflix.json')

In [156]:
df = str(df)

In [159]:
df   =  df.encode('utf-8').decode('utf-8')

NameError: name 'dataframe' is not defined

In [154]:
df.to_html('a.html')

UnicodeEncodeError: 'cp949' codec can't encode character '\xc3' in position 12526: illegal multibyte sequence