In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("apt_final.csv")

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 429466 entries, 0 to 429465
Data columns (total 62 columns):
price_per_area          429466 non-null int64
price                   429466 non-null float64
con_year                429466 non-null int64
year                    429466 non-null int64
dong                    429466 non-null object
aptnm                   429466 non-null object
month                   429466 non-null int64
dat                     429466 non-null object
area                    429466 non-null float64
area_sub                429466 non-null object
loc                     429466 non-null int64
floor                   429466 non-null int64
qrt                     429466 non-null object
yyyyqrt                 429466 non-null object
yyyym                   429466 non-null int64
gu                      429466 non-null object
num_children            429466 non-null int64
num_elementary          429466 non-null int64
num_middle              429466 non-null int64
num_high                429466 non-null int64
edu_subsidy             429466 non-null int64
basic_living            429466 non-null int64
hospital                429466 non-null int64
num_beds                429466 non-null int64
park_area               429466 non-null float64
salary_councilor        429466 non-null int64
obesity                 429466 non-null float64
total_in                429466 non-null int64
total_out               429466 non-null int64
inner_in                429466 non-null int64
inner_out               429466 non-null int64
outer_in                429466 non-null int64
outer_out               429466 non-null int64
city_in                 429466 non-null int64
city_out                429466 non-null int64
consm_price_idx         429466 non-null float64
food_price_idx          429466 non-null float64
prod_price_idx          429466 non-null float64
rental_house_idx        429466 non-null float64
pub_service_idx         429466 non-null float64
pri_service_idx         429466 non-null float64
source_price_idx        429466 non-null float64
life_price_idx          429466 non-null float64
debt                    429466 non-null int64
farm_assets             429466 non-null int64
none_farm_assets        429466 non-null int64
assets                  429466 non-null int64
current_assets          429466 non-null int64
current_debt_ratio      429466 non-null float64
asset_debt_ratio        429466 non-null float64
seoul_cons_result       429466 non-null int64
national_cons_result    429466 non-null int64
seoul_cons_ratio        429466 non-null float64
bond_one_year           429466 non-null float64
bond_three_year         429466 non-null float64
bond_five_year          429466 non-null float64
bond_ten_year           429466 non-null float64
corp_bond_yield_rate    429466 non-null float64
call_rate               429466 non-null float64
interest                429466 non-null float64
interest_on_loan        429466 non-null float64
cd                      429466 non-null float64
dtypes: float64(24), int64(31), object(7)
memory usage: 203.1+ MB

In [4]:
df.columns

Index(['price_per_area', 'price', 'con_year', 'year', 'dong', 'aptnm', 'month',
       'dat', 'area', 'area_sub', 'loc', 'floor', 'qrt', 'yyyyqrt', 'yyyym',
       'gu', 'num_children', 'num_elementary', 'num_middle', 'num_high',
       'edu_subsidy', 'basic_living', 'hospital', 'num_beds', 'park_area',
       'salary_councilor', 'obesity', 'total_in', 'total_out', 'inner_in',
       'inner_out', 'outer_in', 'outer_out', 'city_in', 'city_out',
       'consm_price_idx', 'food_price_idx', 'prod_price_idx',
       'rental_house_idx', 'pub_service_idx', 'pri_service_idx',
       'source_price_idx', 'life_price_idx', 'debt', 'farm_assets',
       'none_farm_assets', 'assets', 'current_assets', 'current_debt_ratio',
       'asset_debt_ratio', 'seoul_cons_result', 'national_cons_result',
       'seoul_cons_ratio', 'bond_one_year', 'bond_three_year',
       'bond_five_year', 'bond_ten_year', 'corp_bond_yield_rate', 'call_rate',
       'interest', 'interest_on_loan', 'cd '],
      dtype='object')

In [5]:
df.head()

,price_per_area,price,con_year,year,dong,aptnm,month,dat,area,area_sub,...,seoul_cons_ratio,bond_one_year,bond_three_year,bond_five_year,bond_ten_year,corp_bond_yield_rate,call_rate,interest,interest_on_loan,cd
0,1979,71000.0,1982,2009,개포동,개포주공 3단지,10,1~10,35.87,small,...,10.061728,3.52,4.47,4.91,5.45,5.6,1.99,3.51,5.88,2.79
1,1994,83700.0,1982,2009,개포동,개포주공 1단지,10,1~10,41.98,small,...,10.061728,3.52,4.47,4.91,5.45,5.6,1.99,3.51,5.88,2.79
2,1128,173500.0,2004,2009,개포동,개포자이(12-2),10,1~10,153.80,large,...,10.061728,3.52,4.47,4.91,5.45,5.6,1.99,3.51,5.88,2.79
3,1204,65000.0,1983,2009,개포동,개포주공 5단지,10,1~10,53.98,small,...,10.061728,3.52,4.47,4.91,5.45,5.6,1.99,3.51,5.88,2.79
4,1214,160000.0,1986,2009,개포동,현대2,10,1~10,131.83,large,...,10.061728,3.52,4.47,4.91,5.45,5.6,1.99,3.51,5.88,2.79

In [6]:
df.columns

Index(['price_per_area', 'price', 'con_year', 'year', 'dong', 'aptnm', 'month',
       'dat', 'area', 'area_sub', 'loc', 'floor', 'qrt', 'yyyyqrt', 'yyyym',
       'gu', 'num_children', 'num_elementary', 'num_middle', 'num_high',
       'edu_subsidy', 'basic_living', 'hospital', 'num_beds', 'park_area',
       'salary_councilor', 'obesity', 'total_in', 'total_out', 'inner_in',
       'inner_out', 'outer_in', 'outer_out', 'city_in', 'city_out',
       'consm_price_idx', 'food_price_idx', 'prod_price_idx',
       'rental_house_idx', 'pub_service_idx', 'pri_service_idx',
       'source_price_idx', 'life_price_idx', 'debt', 'farm_assets',
       'none_farm_assets', 'assets', 'current_assets', 'current_debt_ratio',
       'asset_debt_ratio', 'seoul_cons_result', 'national_cons_result',
       'seoul_cons_ratio', 'bond_one_year', 'bond_three_year',
       'bond_five_year', 'bond_ten_year', 'corp_bond_yield_rate', 'call_rate',
       'interest', 'interest_on_loan', 'cd '],
      dtype='object')

In [7]:
dong_list = ["역삼동", "개포동", "청담동", "삼성동","대치동", "신사동", "논현동", "압구정동", "세곡동", "자곡동", "율현동", "일원동", "수서동", "도곡동", "논현1동", "논현2동", "삼성1동", "삼성2동", "대치1동", "대치2동", "대치4동", "역삼1동", "역삼2동", "도곡1동", "도곡2동", "개포1동", "개포2동", "개포4동", "일원본동", "일원1동", "일원2동"]

In [8]:
dong_list

['역삼동',
 '개포동',
 '청담동',
 '삼성동',
 '대치동',
 '신사동',
 '논현동',
 '압구정동',
 '세곡동',
 '자곡동',
 '율현동',
 '일원동',
 '수서동',
 '도곡동',
 '논현1동',
 '논현2동',
 '삼성1동',
 '삼성2동',
 '대치1동',
 '대치2동',
 '대치4동',
 '역삼1동',
 '역삼2동',
 '도곡1동',
 '도곡2동',
 '개포1동',
 '개포2동',
 '개포4동',
 '일원본동',
 '일원1동',
 '일원2동']

In [9]:
df[df['dong'].isin(dong_list)]

,price_per_area,price,con_year,year,dong,aptnm,month,dat,area,area_sub,...,seoul_cons_ratio,bond_one_year,bond_three_year,bond_five_year,bond_ten_year,corp_bond_yield_rate,call_rate,interest,interest_on_loan,cd
0,1979,71000.0,1982,2009,개포동,개포주공 3단지,10,1~10,35.8700,small,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
1,1994,83700.0,1982,2009,개포동,개포주공 1단지,10,1~10,41.9800,small,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
2,1128,173500.0,2004,2009,개포동,개포자이(12-2),10,1~10,153.8000,large,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
3,1204,65000.0,1983,2009,개포동,개포주공 5단지,10,1~10,53.9800,small,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
4,1214,160000.0,1986,2009,개포동,현대2,10,1~10,131.8300,large,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
5,1480,75000.0,1982,2009,개포동,개포주공 4단지,10,1~10,50.6700,small,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
6,1030,82000.0,1987,2009,개포동,우성8,10,11~20,79.6100,small,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
7,1275,78000.0,1983,2009,개포동,개포주공 5단지,10,11~20,61.1900,small,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
8,1975,100000.0,1982,2009,개포동,개포주공 1단지,10,11~20,50.6400,small,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
9,1133,44800.0,1992,2009,개포동,성원대치2단지아파트,10,11~20,39.5300,small,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
10,1115,37000.0,1992,2009,개포동,성원대치2단지아파트,10,11~20,33.1800,small,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
11,1063,53000.0,1992,2009,개포동,성원대치2단지아파트,10,11~20,49.8600,small,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
12,2223,112000.0,1982,2009,개포동,개포주공 4단지,10,11~20,50.3900,small,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
13,1284,78000.0,1983,2009,개포동,개포주공 7단지,10,11~20,60.7600,small,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
14,1905,80000.0,1982,2009,개포동,개포주공 4단지,10,11~20,41.9900,small,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
15,2240,113500.0,1982,2009,개포동,개포주공 4단지,10,11~20,50.6700,small,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
16,1200,66000.0,1987,2009,개포동,개포6차우성아파트1동~8동,10,11~20,54.9800,small,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
17,938,98000.0,1984,2009,개포동,개포우성3차,10,11~20,104.4300,large,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
18,1320,110500.0,1983,2009,개포동,개포주공 7단지,10,21~31,83.7000,medium,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
19,1394,116000.0,1983,2009,개포동,개포주공 6단지,10,21~31,83.2100,medium,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
20,1880,80000.0,1982,2009,개포동,개포주공 1단지,10,21~31,42.5500,small,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
21,1906,80000.0,1982,2009,개포동,개포주공 1단지,10,21~31,41.9800,small,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
22,1937,98100.0,1982,2009,개포동,개포주공 1단지,10,21~31,50.6400,small,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
23,1945,98500.0,1982,2009,개포동,개포주공 1단지,10,21~31,50.6400,small,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
24,1936,69000.0,1982,2009,개포동,개포주공 1단지,10,21~31,35.6400,small,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
25,1036,52950.0,1992,2009,개포동,삼익대청아파트,10,21~31,51.1200,small,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
26,1016,136500.0,2004,2009,개포동,개포자이(12-2),10,21~31,134.3000,large,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
27,1922,68500.0,1982,2009,개포동,개포주공 1단지,10,21~31,35.6400,small,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
28,1868,79500.0,1982,2009,개포동,개포주공 4단지,10,21~31,42.5500,small,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
29,2058,52000.0,1982,2009,개포동,주공2,10,21~31,25.2700,small,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
427417,499,42200.0,2003,2017,신사동,신사동한신휴플러스,7,1~10,84.6500,medium,...,5.768479,1.46,1.74,1.94,2.25,2.28,1.24,1.48,3.45,1.39
427418,483,28800.0,1996,2017,신사동,신성수정,7,1~10,59.6300,small,...,5.768479,1.46,1.74,1.94,2.25,2.28,1.24,1.48,3.45,1.39
427419,444,34400.0,2006,2017,신사동,정은노블스B,7,1~10,77.4300,small,...,5.768479,1.46,1.74,1.94,2.25,2.28,1.24,1.48,3.45,1.39
427420,411,25200.0,1988,2017,신사동,신성,7,11~20,61.3200,small,...,5.768479,1.46,1.74,1.94,2.25,2.28,1.24,1.48,3.45,1.39
427421,485,28200.0,1993,2017,신사동,신사씨티,7,11~20,58.0900,small,...,5.768479,1.46,1.74,1.94,2.25,2.28,1.24,1.48,3.45,1.39
427422,458,26600.0,1993,2017,신사동,신사씨티,7,11~20,58.0900,small,...,5.768479,1.46,1.74,1.94,2.25,2.28,1.24,1.48,3.45,1.39
427423,404,34000.0,1997,2017,신사동,현대1,7,11~20,84.1700,medium,...,5.768479,1.46,1.74,1.94,2.25,2.28,1.24,1.48,3.45,1.39
427424,463,39000.0,1997,2017,신사동,현대1,7,11~20,84.1700,medium,...,5.768479,1.46,1.74,1.94,2.25,2.28,1.24,1.48,3.45,1.39
427425,409,34700.0,1994,2017,신사동,현대2,7,11~20,84.8300,medium,...,5.768479,1.46,1.74,1.94,2.25,2.28,1.24,1.48,3.45,1.39
427426,410,34800.0,1996,2017,신사동,신성수정,7,11~20,84.8000,medium,...,5.768479,1.46,1.74,1.94,2.25,2.28,1.24,1.48,3.45,1.39
427427,494,31400.0,1987,2017,신사동,라이프미성,7,11~20,63.5300,small,...,5.768479,1.46,1.74,1.94,2.25,2.28,1.24,1.48,3.45,1.39
427428,485,31700.0,2007,2017,신사동,신선,7,11~20,65.3900,small,...,5.768479,1.46,1.74,1.94,2.25,2.28,1.24,1.48,3.45,1.39
427429,525,44600.0,2006,2017,신사동,은평신사두산위브,7,11~20,84.9970,medium,...,5.768479,1.46,1.74,1.94,2.25,2.28,1.24,1.48,3.45,1.39
427430,495,42000.0,2004,2017,신사동,이랜드 타운아파트,7,11~20,84.9287,medium,...,5.768479,1.46,1.74,1.94,2.25,2.28,1.24,1.48,3.45,1.39
427431,503,42600.0,2003,2017,신사동,신사동한신휴플러스,7,11~20,84.6500,medium,...,5.768479,1.46,1.74,1.94,2.25,2.28,1.24,1.48,3.45,1.39
427432,416,35300.0,1994,2017,신사동,현대2,7,11~20,84.8300,medium,...,5.768479,1.46,1.74,1.94,2.25,2.28,1.24,1.48,3.45,1.39
427433,361,30000.0,1992,2017,신사동,라이프씨티,7,21~31,83.0400,medium,...,5.768479,1.46,1.74,1.94,2.25,2.28,1.24,1.48,3.45,1.39
427434,432,28600.0,2008,2017,신사동,신아,7,21~31,66.2700,small,...,5.768479,1.46,1.74,1.94,2.25,2.28,1.24,1.48,3.45,1.39
427435,401,33750.0,1997,2017,신사동,현대1,7,21~31,84.1700,medium,...,5.768479,1.46,1.74,1.94,2.25,2.28,1.24,1.48,3.45,1.39
427436,450,27600.0,1988,2017,신사동,신성,7,21~31,61.3200,small,...,5.768479,1.46,1.74,1.94,2.25,2.28,1.24,1.48,3.45,1.39
427437,429,35900.0,2004,2017,신사동,새한,7,21~31,83.5900,medium,...,5.768479,1.46,1.74,1.94,2.25,2.28,1.24,1.48,3.45,1.39
427438,378,31300.0,1993,2017,신사동,신사씨티,7,21~31,82.7100,medium,...,5.768479,1.46,1.74,1.94,2.25,2.28,1.24,1.48,3.45,1.39
427439,397,32800.0,1993,2017,신사동,신사씨티,7,21~31,82.7100,medium,...,5.768479,1.46,1.74,1.94,2.25,2.28,1.24,1.48,3.45,1.39
427440,406,22800.0,1988,2017,신사동,신성,7,21~31,56.1800,small,...,5.768479,1.46,1.74,1.94,2.25,2.28,1.24,1.48,3.45,1.39
427441,500,42500.0,2011,2017,신사동,두산위브2차,7,21~31,84.9900,medium,...,5.768479,1.46,1.74,1.94,2.25,2.28,1.24,1.48,3.45,1.39
427442,524,44500.0,2006,2017,신사동,은평신사두산위브,7,21~31,84.9970,medium,...,5.768479,1.46,1.74,1.94,2.25,2.28,1.24,1.48,3.45,1.39
427443,385,32000.0,1992,2017,신사동,라이프씨티,7,21~31,83.0400,medium,...,5.768479,1.46,1.74,1.94,2.25,2.28,1.24,1.48,3.45,1.39
427444,487,27000.0,2001,2017,신사동,삼부,7,21~31,55.4400,small,...,5.768479,1.46,1.74,1.94,2.25,2.28,1.24,1.48,3.45,1.39
427445,424,36000.0,2000,2017,신사동,신사성원,7,21~31,84.9600,medium,...,5.768479,1.46,1.74,1.94,2.25,2.28,1.24,1.48,3.45,1.39
427446,526,44700.0,2006,2017,신사동,은평신사두산위브,7,21~31,84.9580,medium,...,5.768479,1.46,1.74,1.94,2.25,2.28,1.24,1.48,3.45,1.39

In [10]:
df.dong.isin(dong_list)

0          True
1          True
2          True
3          True
4          True
5          True
6          True
7          True
8          True
9          True
10         True
11         True
12         True
13         True
14         True
15         True
16         True
17         True
18         True
19         True
20         True
21         True
22         True
23         True
24         True
25         True
26         True
27         True
28         True
29         True
          ...
429436    False
429437    False
429438    False
429439    False
429440    False
429441    False
429442    False
429443    False
429444    False
429445    False
429446    False
429447    False
429448    False
429449    False
429450    False
429451    False
429452    False
429453    False
429454    False
429455    False
429456    False
429457    False
429458    False
429459    False
429460    False
429461    False
429462    False
429463    False
429464    False
429465    False
Name: dong, Length: 429466, dtype: bool

In [11]:
#위에것이 필터하는 조건이다.

In [12]:
df[df.dong.isin(dong_list)]   #  df[  필터하는 조건 ]  #이건 데이터 테이블 .

,price_per_area,price,con_year,year,dong,aptnm,month,dat,area,area_sub,...,seoul_cons_ratio,bond_one_year,bond_three_year,bond_five_year,bond_ten_year,corp_bond_yield_rate,call_rate,interest,interest_on_loan,cd
0,1979,71000.0,1982,2009,개포동,개포주공 3단지,10,1~10,35.8700,small,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
1,1994,83700.0,1982,2009,개포동,개포주공 1단지,10,1~10,41.9800,small,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
2,1128,173500.0,2004,2009,개포동,개포자이(12-2),10,1~10,153.8000,large,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
3,1204,65000.0,1983,2009,개포동,개포주공 5단지,10,1~10,53.9800,small,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
4,1214,160000.0,1986,2009,개포동,현대2,10,1~10,131.8300,large,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
5,1480,75000.0,1982,2009,개포동,개포주공 4단지,10,1~10,50.6700,small,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
6,1030,82000.0,1987,2009,개포동,우성8,10,11~20,79.6100,small,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
7,1275,78000.0,1983,2009,개포동,개포주공 5단지,10,11~20,61.1900,small,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
8,1975,100000.0,1982,2009,개포동,개포주공 1단지,10,11~20,50.6400,small,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
9,1133,44800.0,1992,2009,개포동,성원대치2단지아파트,10,11~20,39.5300,small,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
10,1115,37000.0,1992,2009,개포동,성원대치2단지아파트,10,11~20,33.1800,small,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
11,1063,53000.0,1992,2009,개포동,성원대치2단지아파트,10,11~20,49.8600,small,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
12,2223,112000.0,1982,2009,개포동,개포주공 4단지,10,11~20,50.3900,small,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
13,1284,78000.0,1983,2009,개포동,개포주공 7단지,10,11~20,60.7600,small,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
14,1905,80000.0,1982,2009,개포동,개포주공 4단지,10,11~20,41.9900,small,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
15,2240,113500.0,1982,2009,개포동,개포주공 4단지,10,11~20,50.6700,small,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
16,1200,66000.0,1987,2009,개포동,개포6차우성아파트1동~8동,10,11~20,54.9800,small,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
17,938,98000.0,1984,2009,개포동,개포우성3차,10,11~20,104.4300,large,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
18,1320,110500.0,1983,2009,개포동,개포주공 7단지,10,21~31,83.7000,medium,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
19,1394,116000.0,1983,2009,개포동,개포주공 6단지,10,21~31,83.2100,medium,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
20,1880,80000.0,1982,2009,개포동,개포주공 1단지,10,21~31,42.5500,small,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
21,1906,80000.0,1982,2009,개포동,개포주공 1단지,10,21~31,41.9800,small,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
22,1937,98100.0,1982,2009,개포동,개포주공 1단지,10,21~31,50.6400,small,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
23,1945,98500.0,1982,2009,개포동,개포주공 1단지,10,21~31,50.6400,small,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
24,1936,69000.0,1982,2009,개포동,개포주공 1단지,10,21~31,35.6400,small,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
25,1036,52950.0,1992,2009,개포동,삼익대청아파트,10,21~31,51.1200,small,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
26,1016,136500.0,2004,2009,개포동,개포자이(12-2),10,21~31,134.3000,large,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
27,1922,68500.0,1982,2009,개포동,개포주공 1단지,10,21~31,35.6400,small,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
28,1868,79500.0,1982,2009,개포동,개포주공 4단지,10,21~31,42.5500,small,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
29,2058,52000.0,1982,2009,개포동,주공2,10,21~31,25.2700,small,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
427417,499,42200.0,2003,2017,신사동,신사동한신휴플러스,7,1~10,84.6500,medium,...,5.768479,1.46,1.74,1.94,2.25,2.28,1.24,1.48,3.45,1.39
427418,483,28800.0,1996,2017,신사동,신성수정,7,1~10,59.6300,small,...,5.768479,1.46,1.74,1.94,2.25,2.28,1.24,1.48,3.45,1.39
427419,444,34400.0,2006,2017,신사동,정은노블스B,7,1~10,77.4300,small,...,5.768479,1.46,1.74,1.94,2.25,2.28,1.24,1.48,3.45,1.39
427420,411,25200.0,1988,2017,신사동,신성,7,11~20,61.3200,small,...,5.768479,1.46,1.74,1.94,2.25,2.28,1.24,1.48,3.45,1.39
427421,485,28200.0,1993,2017,신사동,신사씨티,7,11~20,58.0900,small,...,5.768479,1.46,1.74,1.94,2.25,2.28,1.24,1.48,3.45,1.39
427422,458,26600.0,1993,2017,신사동,신사씨티,7,11~20,58.0900,small,...,5.768479,1.46,1.74,1.94,2.25,2.28,1.24,1.48,3.45,1.39
427423,404,34000.0,1997,2017,신사동,현대1,7,11~20,84.1700,medium,...,5.768479,1.46,1.74,1.94,2.25,2.28,1.24,1.48,3.45,1.39
427424,463,39000.0,1997,2017,신사동,현대1,7,11~20,84.1700,medium,...,5.768479,1.46,1.74,1.94,2.25,2.28,1.24,1.48,3.45,1.39
427425,409,34700.0,1994,2017,신사동,현대2,7,11~20,84.8300,medium,...,5.768479,1.46,1.74,1.94,2.25,2.28,1.24,1.48,3.45,1.39
427426,410,34800.0,1996,2017,신사동,신성수정,7,11~20,84.8000,medium,...,5.768479,1.46,1.74,1.94,2.25,2.28,1.24,1.48,3.45,1.39
427427,494,31400.0,1987,2017,신사동,라이프미성,7,11~20,63.5300,small,...,5.768479,1.46,1.74,1.94,2.25,2.28,1.24,1.48,3.45,1.39
427428,485,31700.0,2007,2017,신사동,신선,7,11~20,65.3900,small,...,5.768479,1.46,1.74,1.94,2.25,2.28,1.24,1.48,3.45,1.39
427429,525,44600.0,2006,2017,신사동,은평신사두산위브,7,11~20,84.9970,medium,...,5.768479,1.46,1.74,1.94,2.25,2.28,1.24,1.48,3.45,1.39
427430,495,42000.0,2004,2017,신사동,이랜드 타운아파트,7,11~20,84.9287,medium,...,5.768479,1.46,1.74,1.94,2.25,2.28,1.24,1.48,3.45,1.39
427431,503,42600.0,2003,2017,신사동,신사동한신휴플러스,7,11~20,84.6500,medium,...,5.768479,1.46,1.74,1.94,2.25,2.28,1.24,1.48,3.45,1.39
427432,416,35300.0,1994,2017,신사동,현대2,7,11~20,84.8300,medium,...,5.768479,1.46,1.74,1.94,2.25,2.28,1.24,1.48,3.45,1.39
427433,361,30000.0,1992,2017,신사동,라이프씨티,7,21~31,83.0400,medium,...,5.768479,1.46,1.74,1.94,2.25,2.28,1.24,1.48,3.45,1.39
427434,432,28600.0,2008,2017,신사동,신아,7,21~31,66.2700,small,...,5.768479,1.46,1.74,1.94,2.25,2.28,1.24,1.48,3.45,1.39
427435,401,33750.0,1997,2017,신사동,현대1,7,21~31,84.1700,medium,...,5.768479,1.46,1.74,1.94,2.25,2.28,1.24,1.48,3.45,1.39
427436,450,27600.0,1988,2017,신사동,신성,7,21~31,61.3200,small,...,5.768479,1.46,1.74,1.94,2.25,2.28,1.24,1.48,3.45,1.39
427437,429,35900.0,2004,2017,신사동,새한,7,21~31,83.5900,medium,...,5.768479,1.46,1.74,1.94,2.25,2.28,1.24,1.48,3.45,1.39
427438,378,31300.0,1993,2017,신사동,신사씨티,7,21~31,82.7100,medium,...,5.768479,1.46,1.74,1.94,2.25,2.28,1.24,1.48,3.45,1.39
427439,397,32800.0,1993,2017,신사동,신사씨티,7,21~31,82.7100,medium,...,5.768479,1.46,1.74,1.94,2.25,2.28,1.24,1.48,3.45,1.39
427440,406,22800.0,1988,2017,신사동,신성,7,21~31,56.1800,small,...,5.768479,1.46,1.74,1.94,2.25,2.28,1.24,1.48,3.45,1.39
427441,500,42500.0,2011,2017,신사동,두산위브2차,7,21~31,84.9900,medium,...,5.768479,1.46,1.74,1.94,2.25,2.28,1.24,1.48,3.45,1.39
427442,524,44500.0,2006,2017,신사동,은평신사두산위브,7,21~31,84.9970,medium,...,5.768479,1.46,1.74,1.94,2.25,2.28,1.24,1.48,3.45,1.39
427443,385,32000.0,1992,2017,신사동,라이프씨티,7,21~31,83.0400,medium,...,5.768479,1.46,1.74,1.94,2.25,2.28,1.24,1.48,3.45,1.39
427444,487,27000.0,2001,2017,신사동,삼부,7,21~31,55.4400,small,...,5.768479,1.46,1.74,1.94,2.25,2.28,1.24,1.48,3.45,1.39
427445,424,36000.0,2000,2017,신사동,신사성원,7,21~31,84.9600,medium,...,5.768479,1.46,1.74,1.94,2.25,2.28,1.24,1.48,3.45,1.39
427446,526,44700.0,2006,2017,신사동,은평신사두산위브,7,21~31,84.9580,medium,...,5.768479,1.46,1.74,1.94,2.25,2.28,1.24,1.48,3.45,1.39

In [13]:
df[df.dong.isin(dong_list)].price_per_area.mean()   # 평균

1159.915258074253

In [14]:
#in 은 iterable .

[1,2,3] in [[1,2,3],4]    #[][] 두개써서 이터러블 만듬?

True

In [15]:
df.dong

0         개포동
1         개포동
2         개포동
3         개포동
4         개포동
5         개포동
6         개포동
7         개포동
8         개포동
9         개포동
10        개포동
11        개포동
12        개포동
13        개포동
14        개포동
15        개포동
16        개포동
17        개포동
18        개포동
19        개포동
20        개포동
21        개포동
22        개포동
23        개포동
24        개포동
25        개포동
26        개포동
27        개포동
28        개포동
29        개포동
         ...
429436    중화동
429437    중화동
429438    중화동
429439    중화동
429440    중화동
429441    중화동
429442    중화동
429443    중화동
429444    중화동
429445    중화동
429446    중화동
429447    중화동
429448    중화동
429449    중화동
429450    중화동
429451    중화동
429452    중화동
429453    중화동
429454    중화동
429455    중화동
429456    중화동
429457    중화동
429458    중화동
429459    중화동
429460    중화동
429461    중화동
429462    중화동
429463    중화동
429464    중화동
429465    중화동
Name: dong, Length: 429466, dtype: object

In [16]:
df.dong in dong_list # 에러뜸

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [17]:
df.dong in(dong_list)  #결국 is in 은 함수형 패러다임으로 만듬.

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [18]:
list(map(lambda x:x in dong_list ,df.dong))

[True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 ...]

In [19]:
#한개씩 나오기때문에 , 전체의 iterable 데이터를 하나씩 처리하려면 map 을 쓴다 , 저것이 isin 을 함수로 만들어논것이다 .

In [20]:
# is in 은 전체 칼럼중에서 있는냐없느냐 체크해주는 함수다 .

--------------------

In [21]:
#filter = df.isin({'State':['CA'],'Metro':['San Francisco']}) #in 다음에 dict 가 오면  key 만 체크함.  pandas(3) 에 내용추가.

In [22]:
# row : loc , iloc, data [ ]  : 조건에 맞는 행 뽑기.

예시 df[df.State=='CA']

In [23]:
df2 =  df[["year","price"]]

In [24]:
df2.groupby(by="year").mean()

             price
year
2009  53154.423087
2010  54481.975525
2011  47782.875191
2012  49748.876154
2013  47549.218954
2014  46254.399498
2015  47321.686795
2016  56794.748497
2017  65054.597161

In [25]:
df2.groupby(by="year") # 이런 object 는 덜 완전하다는것이다 . 음 뒤에 mean() 으로 하니까 나옴

In [26]:
#단순한 통계치 , 두번쨰는 합한 통계치 세번쨰는 아파트가격에 연도별 평균을 나타내는것 까지봄

# df2.plot.bar() 졸라느리다

%matplotlib inline

data2.plot.bar()