In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("data-netflix.csv")

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
title                1000 non-null object
rating               1000 non-null object
ratingLevel          941 non-null object
ratingDescription    1000 non-null int64
release year         1000 non-null int64
user rating score    605 non-null float64
user rating size     1000 non-null int64
dtypes: float64(1), int64(3), object(3)
memory usage: 54.8+ KB

In [5]:
df.describe()

       ratingDescription  release year  user rating score  user rating size
count         1000.00000   1000.000000         605.000000       1000.000000
mean            67.36600   2010.335000          84.094215         80.783000
std             30.78561      8.877927          12.344371          0.973066
min             10.00000   1940.000000          55.000000         80.000000
25%             35.00000   2007.000000          75.000000         80.000000
50%             60.00000   2015.000000          88.000000         80.000000
75%             90.00000   2016.000000          95.000000         82.000000
max            124.00000   2017.000000          99.000000         82.000000

In [6]:
df.head()

,title,rating,ratingLevel,ratingDescription,release year,user rating score,user rating size
0,White Chicks,PG-13,"crude and sexual humor, language and some drug...",80,2004,82.0,80
1,Lucky Number Slevin,R,"strong violence, sexual content and adult lang...",100,2006,NaN,82
2,Grey's Anatomy,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,98.0,80
3,Prison Break,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2008,98.0,80
4,How I Met Your Mother,TV-PG,Parental guidance suggested. May not be suitab...,70,2014,94.0,80

In [7]:
df.tail()

,title,rating,ratingLevel,ratingDescription,release year,user rating score,user rating size
995,The BFG,PG,"for action/peril, some scary moments and brief...",60,2016,97.0,80
996,The Secret Life of Pets,PG,for action and some rude humor,60,2016,NaN,81
997,Precious Puppies,TV-G,Suitable for all ages.,35,2003,NaN,82
998,Beary Tales,TV-G,Suitable for all ages.,35,2013,NaN,82
999,Growing Up Wild,G,NaN,35,2016,80.0,80

In [9]:
df.sample(5)

,title,rating,ratingLevel,ratingDescription,release year,user rating score,user rating size
84,Stranger Things,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,90.0,80
543,The Angry Birds Movie,PG,for rude humor and action,60,2016,92.0,80
810,The Brave Little Toaster to the Rescue,G,General Audiences. Suitable for all ages.,35,1997,NaN,82
532,All Hail King Julien,TV-Y7-FV,Suitable for children ages 7 and older. Conte...,42,2016,71.0,80
754,The Prince of Egypt,PG,intense scenes dealing with strong content,60,1998,81.0,80

In [10]:
type(df)

pandas.core.frame.DataFrame

In [11]:
dir(df)

['T',
 '_AXIS_ALIASES',
 '_AXIS_IALIASES',
 '_AXIS_LEN',
 '_AXIS_NAMES',
 '_AXIS_NUMBERS',
 '_AXIS_ORDERS',
 '_AXIS_REVERSED',
 '_AXIS_SLICEMAP',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_wrap__',
 '__bool__',
 '__bytes__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__div__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdiv__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__unicode__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_add_numeric_operations',
 '_add_series_only_operations',
 '_add_series_or_dataframe_operations',
 '_agg_by_level',
 '_agg_doc',
 '_aggregate',
 '_aggregate_multiple_funcs',
 '_align_frame',
 '_align_series',
 '_box_col_values',
 '_box_item_values',
 '_builtin_table',
 '_check_inplace_setting',
 '_check_is_chained_assignment_possible',
 '_check_label_or_level_ambiguity',
 '_check_percentile',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_combine_const',
 '_combine_frame',
 '_combine_match_columns',
 '_combine_match_index',
 '_compare_frame',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_axes_dict_for_slice',
 '_construct_axes_dict_from',
 '_construct_axes_from_arguments',
 '_constructor',
 '_constructor_expanddim',
 '_constructor_sliced',
 '_convert',
 '_count_level',
 '_create_indexer',
 '_cython_table',
 '_deprecations',
 '_dir_additions',
 '_dir_deletions',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_ensure_valid_index',
 '_expand_axes',
 '_find_valid_index',
 '_from_arrays',
 '_from_axes',
 '_get_agg_axis',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cacher',
 '_get_index_resolvers',
 '_get_item_cache',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_get_values',
 '_getitem_array',
 '_getitem_column',
 '_getitem_frame',
 '_getitem_multilevel',
 '_getitem_slice',
 '_gotitem',
 '_iget_item_cache',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_info_repr',
 '_init_dict',
 '_init_mgr',
 '_init_ndarray',
 '_internal_names',
 '_internal_names_set',
 '_is_builtin_func',
 '_is_cached',
 '_is_copy',
 '_is_cython_func',
 '_is_datelike_mixed_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_is_numeric_mixed_type',
 '_is_view',
 '_ix',
 '_ixs',
 '_join_compat',
 '_maybe_cache_changed',
 '_maybe_update_cacher',
 '_metadata',
 '_needs_reindex_multi',
 '_obj_with_exclusions',
 '_protect_consolidate',
 '_reduce',
 '_reindex_axes',
 '_reindex_axis',
 '_reindex_columns',
 '_reindex_index',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_repr_data_resource_',
 '_repr_fits_horizontal_',
 '_repr_fits_vertical_',
 '_repr_html_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_sanitize_column',
 '_selected_obj',
 '_selection',
 '_selection_list',
 '_selection_name',
 '_series',
 '_set_as_cached',
 '_set_axis',
 '_set_axis_name',
 '_set_is_copy',
 '_set_item',
 '_set_value',
 '_setitem_array',
 '_setitem_frame',
 '_setitem_slice',
 '_setup_axes',
 '_shallow_copy',
 '_slice',
 '_stat_axis',
 '_stat_axis_name',
 '_stat_axis_number',
 '_take',
 '_to_dict_of_blocks',
 '_try_aggregate_string_function',
 '_typ',
 '_unpickle_frame_compat',
 '_unpickle_matrix_compat',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 '_xs',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'append',
 'apply',
 'applymap',
 'as_matrix',
 'asfreq',
 'asof',
 'assign',
 'astype',
 'at',
 'at_time',
 'axes',
 'between_time',
 'bfill',
 'bool',
 'boxplot',
 'clip',
 'clip_lower',
 'clip_upper',
 'columns',
 'combine',
 'combine_first',
 'compound',
 'copy',
 'corr',
 'corrwith',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'dot',
 'drop',
 'drop_duplicates',
 'dropna',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'eval',
 'ewm',
 'expanding',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'floordiv',
 'from_dict',
 'from_records',
 'ftypes',
 'ge',
 'get',
 'get_dtype_counts',
 'get_ftype_counts',
 'get_values',
 'groupby',
 'gt',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'insert',
 'interpolate',
 'isin',
 'isna',
 'isnull',
 'items',
 'iteritems',
 'iterrows',
 'itertuples',
 'ix',
 'join',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'loc',
 'lookup',
 'lt',
 'mad',
 'mask',
 'max',
 'mean',
 'median',
 'melt',
 'memory_usage',
 'merge',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pct_change',
 'pipe',
 'pivot',
 'pivot_table',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'query',
 'radd',
 'rank',
 'rating',
 'ratingDescription',
 'ratingLevel',
 'rdiv',
 'reindex',
 'reindex_axis',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'select',
 'select_dtypes',
 'sem',
 'set_axis',
 'set_index',
 'shape',
 'shift',
 'size',
 'skew',
 'slice_shift',
 'sort_index',
 'sort_values',
 'squeeze',
 'stack',
 'std',
 'style',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'title',
 'to_clipboard',
 'to_csv',
 'to_dense',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_gbq',
 'to_hdf',
 'to_html',
 'to_json',
 'to_latex',
 'to_msgpack',
 'to_panel',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sparse',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tshift',
 'tz_convert',
 'tz_localize',
 'unstack',
 'update',
 'values',
 'var',
 'where',
 'xs']

In [15]:
df['title'] # 딕셔너리 방식

0                                    White Chicks
1                             Lucky Number Slevin
2                                  Grey's Anatomy
3                                    Prison Break
4                           How I Met Your Mother
5                                    Supernatural
6                                    Breaking Bad
7                             The Vampire Diaries
8                                The Walking Dead
9                             Pretty Little Liars
10                               Once Upon a Time
11                                       Sherlock
12                                     Death Note
13                                         Naruto
14                                     The Hunter
15                          Lottie Dottie Chicken
16                                          Arrow
17                                   Black Mirror
18                                  The Originals
19                                        The 100
20                             Masha and the Bear
21                                         dfdfdf
22                         Nymphomaniac: Volume 1
23                         Hunter X Hunter (2011)
24                             Marvel's Luke Cage
25                             Marvel's Iron Fist
26                                         Narcos
27                                      The Flash
28                          The Seven Deadly Sins
29                                         Scream
                          ...
970                                         Annie
971            An American Tail: Fievel Goes West
972                          D2: The Mighty Ducks
973                      Honey, I Shrunk the Kids
974                                The Iron Giant
975                       The Fox and the Hound 2
976                                   Air Buddies
977               Dr. Dolittle: Tail to the Chief
978                                      Flicka 2
979                           H2O: Just Add Water
980                                  The Gruffalo
981                                  Dolphin Tale
982                                 Pound Puppies
983    Beverly Hills Chihuahua 3: Viva La Fiesta!
984                          The Magic School Bus
985                                     Step Dogs
986                       Poketmon: Indigo League
987                                    Mia and Me
988                                    Paddington
989                               Russell Madness
990                             My Animal Friends
991                            Dawn of the Croods
992                    Alpha and Omega: Dino Digs
993                     Wiener Dog Internationals
994                                      Pup Star
995                                       The BFG
996                       The Secret Life of Pets
997                              Precious Puppies
998                                   Beary Tales
999                               Growing Up Wild
Name: title, Length: 1000, dtype: object

In [18]:
#이것은 시리즈다, 시리즈는 색이없다

In [17]:
type(df['title'])

pandas.core.series.Series

In [20]:
type(df[['title']])

pandas.core.frame.DataFrame

In [21]:
df.title

0                                    White Chicks
1                             Lucky Number Slevin
2                                  Grey's Anatomy
3                                    Prison Break
4                           How I Met Your Mother
5                                    Supernatural
6                                    Breaking Bad
7                             The Vampire Diaries
8                                The Walking Dead
9                             Pretty Little Liars
10                               Once Upon a Time
11                                       Sherlock
12                                     Death Note
13                                         Naruto
14                                     The Hunter
15                          Lottie Dottie Chicken
16                                          Arrow
17                                   Black Mirror
18                                  The Originals
19                                        The 100
20                             Masha and the Bear
21                                         dfdfdf
22                         Nymphomaniac: Volume 1
23                         Hunter X Hunter (2011)
24                             Marvel's Luke Cage
25                             Marvel's Iron Fist
26                                         Narcos
27                                      The Flash
28                          The Seven Deadly Sins
29                                         Scream
                          ...
970                                         Annie
971            An American Tail: Fievel Goes West
972                          D2: The Mighty Ducks
973                      Honey, I Shrunk the Kids
974                                The Iron Giant
975                       The Fox and the Hound 2
976                                   Air Buddies
977               Dr. Dolittle: Tail to the Chief
978                                      Flicka 2
979                           H2O: Just Add Water
980                                  The Gruffalo
981                                  Dolphin Tale
982                                 Pound Puppies
983    Beverly Hills Chihuahua 3: Viva La Fiesta!
984                          The Magic School Bus
985                                     Step Dogs
986                       Poketmon: Indigo League
987                                    Mia and Me
988                                    Paddington
989                               Russell Madness
990                             My Animal Friends
991                            Dawn of the Croods
992                    Alpha and Omega: Dino Digs
993                     Wiener Dog Internationals
994                                      Pup Star
995                                       The BFG
996                       The Secret Life of Pets
997                              Precious Puppies
998                                   Beary Tales
999                               Growing Up Wild
Name: title, Length: 1000, dtype: object

dataframe 에 접근하기위해서 위와같이 객체에 접근하는 어트리뷰트 방식과 , 딕셔너리 방식이있음.

In [23]:
df.columns

Index(['title', 'rating', 'ratingLevel', 'ratingDescription', 'release year',
       'user rating score', 'user rating size'],
      dtype='object')

In [24]:
#dictionary 방식, attribute 방식, 두가지, 

df[['rating','title']]  # 리스트는 시퀀스 , 즉 순서가 있다.

    rating                                       title
0    PG-13                                White Chicks
1        R                         Lucky Number Slevin
2    TV-14                              Grey's Anatomy
3    TV-14                                Prison Break
4    TV-PG                       How I Met Your Mother
5    TV-14                                Supernatural
6    TV-MA                                Breaking Bad
7    TV-14                         The Vampire Diaries
8    TV-MA                            The Walking Dead
9    TV-14                         Pretty Little Liars
10   TV-PG                            Once Upon a Time
11   TV-14                                    Sherlock
12   TV-14                                  Death Note
13   TV-PG                                      Naruto
14       R                                  The Hunter
15    TV-Y                       Lottie Dottie Chicken
16   TV-14                                       Arrow
17   TV-MA                                Black Mirror
18   TV-14                               The Originals
19      NR                                     The 100
20    TV-Y                          Masha and the Bear
21   TV-MA                                      dfdfdf
22      NR                      Nymphomaniac: Volume 1
23      NR                      Hunter X Hunter (2011)
24   TV-MA                          Marvel's Luke Cage
25   TV-MA                          Marvel's Iron Fist
26   TV-MA                                      Narcos
27   TV-PG                                   The Flash
28   TV-14                       The Seven Deadly Sins
29   TV-14                                      Scream
..     ...                                         ...
970     PG                                       Annie
971      G          An American Tail: Fievel Goes West
972     PG                        D2: The Mighty Ducks
973     PG                    Honey, I Shrunk the Kids
974     PG                              The Iron Giant
975      G                     The Fox and the Hound 2
976     PG                                 Air Buddies
977     PG             Dr. Dolittle: Tail to the Chief
978     PG                                    Flicka 2
979  TV-PG                         H2O: Just Add Water
980   TV-Y                                The Gruffalo
981     PG                                Dolphin Tale
982   TV-Y                               Pound Puppies
983      G  Beverly Hills Chihuahua 3: Viva La Fiesta!
984   TV-Y                        The Magic School Bus
985  TV-PG                                   Step Dogs
986   TV-Y                     Poketmon: Indigo League
987   TV-Y                                  Mia and Me
988     PG                                  Paddington
989     PG                             Russell Madness
990   TV-Y                           My Animal Friends
991  TV-Y7                          Dawn of the Croods
992   TV-G                  Alpha and Omega: Dino Digs
993      G                   Wiener Dog Internationals
994      G                                    Pup Star
995     PG                                     The BFG
996     PG                     The Secret Life of Pets
997   TV-G                            Precious Puppies
998   TV-G                                 Beary Tales
999      G                             Growing Up Wild

[1000 rows x 2 columns]

In [25]:
df[['title']]

                                          title
0                                  White Chicks
1                           Lucky Number Slevin
2                                Grey's Anatomy
3                                  Prison Break
4                         How I Met Your Mother
5                                  Supernatural
6                                  Breaking Bad
7                           The Vampire Diaries
8                              The Walking Dead
9                           Pretty Little Liars
10                             Once Upon a Time
11                                     Sherlock
12                                   Death Note
13                                       Naruto
14                                   The Hunter
15                        Lottie Dottie Chicken
16                                        Arrow
17                                 Black Mirror
18                                The Originals
19                                      The 100
20                           Masha and the Bear
21                                       dfdfdf
22                       Nymphomaniac: Volume 1
23                       Hunter X Hunter (2011)
24                           Marvel's Luke Cage
25                           Marvel's Iron Fist
26                                       Narcos
27                                    The Flash
28                        The Seven Deadly Sins
29                                       Scream
..                                          ...
970                                       Annie
971          An American Tail: Fievel Goes West
972                        D2: The Mighty Ducks
973                    Honey, I Shrunk the Kids
974                              The Iron Giant
975                     The Fox and the Hound 2
976                                 Air Buddies
977             Dr. Dolittle: Tail to the Chief
978                                    Flicka 2
979                         H2O: Just Add Water
980                                The Gruffalo
981                                Dolphin Tale
982                               Pound Puppies
983  Beverly Hills Chihuahua 3: Viva La Fiesta!
984                        The Magic School Bus
985                                   Step Dogs
986                     Poketmon: Indigo League
987                                  Mia and Me
988                                  Paddington
989                             Russell Madness
990                           My Animal Friends
991                          Dawn of the Croods
992                  Alpha and Omega: Dino Digs
993                   Wiener Dog Internationals
994                                    Pup Star
995                                     The BFG
996                     The Secret Life of Pets
997                            Precious Puppies
998                                 Beary Tales
999                             Growing Up Wild

[1000 rows x 1 columns]

In [28]:
#시리즈와 데이터프레임이 지원하는 기능은 다르다, 시리즈와 비슷해보이지만, 데이터프레임으로 가져오기위해서는 리스트형식으로 넣어야한다.
#관례상 어트리뷰트 방식보다 , 딕셔너리 방식이 조금더 좋다
#어트리뷰트 방식은 df.컬럼명 이기 때문에 , 하나밖에못가져옴, 
#이에 비해 딕셔너리방식은 순서도 지원하고, 여러개 가져올수있음

In [33]:
df[0] # 딕셔너리는 컬럼명으로 뽑는 방식인데 컬렴명에 0 이없으니 당연히 에러.

KeyError: 10

In [37]:
df.loc[0]

title                                                     White Chicks
rating                                                           PG-13
ratingLevel          crude and sexual humor, language and some drug...
ratingDescription                                                   80
release year                                                      2004
user rating score                                                   82
user rating size                                                    80
Name: 0, dtype: object

In [38]:
# loc 는 row. loc 없이는 column.

In [48]:
df.loc[[0,2,4]] #pandas 에서는 리스트형식으로 넣어야 동시에 여러값을 가져옴

,title,rating,ratingLevel,ratingDescription,release year,user rating score,user rating size
0,White Chicks,PG-13,"crude and sexual humor, language and some drug...",80,2004,82.0,80
2,Grey's Anatomy,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,98.0,80
4,How I Met Your Mother,TV-PG,Parental guidance suggested. May not be suitab...,70,2014,94.0,80

In [43]:
#row 는 loc 쓴다.

In [49]:
df.loc[0:4]

,title,rating,ratingLevel,ratingDescription,release year,user rating score,user rating size
0,White Chicks,PG-13,"crude and sexual humor, language and some drug...",80,2004,82.0,80
1,Lucky Number Slevin,R,"strong violence, sexual content and adult lang...",100,2006,NaN,82
2,Grey's Anatomy,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,98.0,80
3,Prison Break,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2008,98.0,80
4,How I Met Your Mother,TV-PG,Parental guidance suggested. May not be suitab...,70,2014,94.0,80

In [51]:
#컬럼은 slicing  이 안된다 . 딕셔너리 구조라서 , 
#하지만 row 는 slicing  이 된다 . 

df.loc[1:3,'title']  #2차원 slicing title 열 1에서 3 까지 가져온다

1    Lucky Number Slevin
2         Grey's Anatomy
3           Prison Break
Name: title, dtype: object

In [52]:
df.loc[1:3,['title','rating']] #두개이상 가져올때는 리스트를 쓴다 .

                 title rating
1  Lucky Number Slevin      R
2       Grey's Anatomy  TV-14
3         Prison Break  TV-14

In [59]:
df.loc[:,["title","rating"]] # 이건 딕셔너리방식하고 같다

                                          title rating
0                                  White Chicks  PG-13
1                           Lucky Number Slevin      R
2                                Grey's Anatomy  TV-14
3                                  Prison Break  TV-14
4                         How I Met Your Mother  TV-PG
5                                  Supernatural  TV-14
6                                  Breaking Bad  TV-MA
7                           The Vampire Diaries  TV-14
8                              The Walking Dead  TV-MA
9                           Pretty Little Liars  TV-14
10                             Once Upon a Time  TV-PG
11                                     Sherlock  TV-14
12                                   Death Note  TV-14
13                                       Naruto  TV-PG
14                                   The Hunter      R
15                        Lottie Dottie Chicken   TV-Y
16                                        Arrow  TV-14
17                                 Black Mirror  TV-MA
18                                The Originals  TV-14
19                                      The 100     NR
20                           Masha and the Bear   TV-Y
21                                       dfdfdf  TV-MA
22                       Nymphomaniac: Volume 1     NR
23                       Hunter X Hunter (2011)     NR
24                           Marvel's Luke Cage  TV-MA
25                           Marvel's Iron Fist  TV-MA
26                                       Narcos  TV-MA
27                                    The Flash  TV-PG
28                        The Seven Deadly Sins  TV-14
29                                       Scream  TV-14
..                                          ...    ...
970                                       Annie     PG
971          An American Tail: Fievel Goes West      G
972                        D2: The Mighty Ducks     PG
973                    Honey, I Shrunk the Kids     PG
974                              The Iron Giant     PG
975                     The Fox and the Hound 2      G
976                                 Air Buddies     PG
977             Dr. Dolittle: Tail to the Chief     PG
978                                    Flicka 2     PG
979                         H2O: Just Add Water  TV-PG
980                                The Gruffalo   TV-Y
981                                Dolphin Tale     PG
982                               Pound Puppies   TV-Y
983  Beverly Hills Chihuahua 3: Viva La Fiesta!      G
984                        The Magic School Bus   TV-Y
985                                   Step Dogs  TV-PG
986                     Poketmon: Indigo League   TV-Y
987                                  Mia and Me   TV-Y
988                                  Paddington     PG
989                             Russell Madness     PG
990                           My Animal Friends   TV-Y
991                          Dawn of the Croods  TV-Y7
992                  Alpha and Omega: Dino Digs   TV-G
993                   Wiener Dog Internationals      G
994                                    Pup Star      G
995                                     The BFG     PG
996                     The Secret Life of Pets     PG
997                            Precious Puppies   TV-G
998                                 Beary Tales   TV-G
999                             Growing Up Wild      G

[1000 rows x 2 columns]

In [60]:
# 위의것은 데이터프레임이니까, 함수 적용가능

In [61]:
# loc 가 있고  iloc 가있다. i = index 베이스, l = label 인덱스

In [67]:
%timeit df.at[1,'rating'] #이거는 하나만 가져올때 ,인덱싱하는것, 슬라이싱 X

7.55 µs ± 1.33 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)

In [68]:
%timeit df.loc[1,'rating'] # 이거는 범위를 가져올 수 있음.

11.6 µs ± 1.13 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)

In [ ]:
#성능 체크 , at은 속도가 빠르다 , loc 이 조금 느리다

In [69]:
df.loc[1,'rating']  = 19 # 이렇게 값을 바꿀 수 있다, 수정할때 사용가능 ,

In [71]:
df.axes

[RangeIndex(start=0, stop=1000, step=1),
 Index(['title', 'rating', 'ratingLevel', 'ratingDescription', 'release year',
        'user rating score', 'user rating size'],
       dtype='object')]

In [72]:
df.iat[1,1] # 앞의 것은 row , 뒤의것은 column 으로본다. i  = index based

19

In [75]:
df.at[1,1] #  이것은 label 베이스 이기 때문에 row 와 columng 에 대한 index 를 넣으면 이렇게 에러가 발생한다 .

ValueError: At based indexing on an non-integer index can only have non-integer indexers

In [77]:
timeit df.iat[1,1]

8.88 µs ± 1.42 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)

iat 은 변환단계를 거쳐서 조금느림 하지만 눈에 보이기 좋아서 iat 을 훨씬더 많이씀

In [79]:
%timeit df.at[1,'title']

7.2 µs ± 1.13 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)

In [87]:
df.loc[1:3,'rating']

1       19
2    TV-14
3    TV-14
Name: rating, dtype: object

In [90]:
df.iloc[1:3,1] # iloc 는 인덱스베이스니까 sequence 리스트랑 같다 . 따라서 마지막 3이 출력 되지않는다 이것은 loc 와 혼동하기쉽다.

1       19
2    TV-14
Name: rating, dtype: object