In [1]:
import pandas as pd
import numpy as np

In [2]:
np.random.seed(0) # 랜덤값 시드 변경.. 중복 랜덤값 방지

In [108]:
data_dirty = pd.read_json('data/nobel_winners_dirty.json')

In [4]:
data_dirty.describe(include='all')

,born_in,category,country,date_of_birth,date_of_death,gender,link,name,place_of_birth,place_of_death,text,year
count,1052,1052,1052,1044,1044,1040,1052,1052,1044,1044,1052,1052.000000
unique,40,7,59,853,563,2,893,998,735,410,1043,NaN
top,,Physiology or Medicine,United States,7 November 1867,,male,http://en.wikipedia.org/wiki/Michael_Levitt,Ernest Rutherford,,,"Henry Dunant , Peace, 1901",NaN
freq,910,250,350,4,362,982,4,2,29,409,2,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1968.729087
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33.155829
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1809.000000
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1947.000000
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1975.000000
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1996.000000
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014.000000

In [5]:
data_dirty.describe(include=['object'])

,born_in,category,country,date_of_birth,date_of_death,gender,link,name,place_of_birth,place_of_death,text
count,1052,1052,1052,1044,1044,1040,1052,1052,1044,1044,1052
unique,40,7,59,853,563,2,893,998,735,410,1043
top,,Physiology or Medicine,United States,7 November 1867,,male,http://en.wikipedia.org/wiki/Michael_Levitt,Ernest Rutherford,,,"Henry Dunant , Peace, 1901"
freq,910,250,350,4,362,982,4,2,29,409,2

In [6]:
data_dirty.head()

,born_in,category,country,date_of_birth,date_of_death,gender,link,name,place_of_birth,place_of_death,text,year
0,,Physiology or Medicine,Argentina,8 October 1927,24 March 2002,male,http://en.wikipedia.org/wiki/C%C3%A9sar_Milstein,César Milstein,"Bahía Blanca , Argentina","Cambridge , England","César Milstein , Physiology or Medicine, 1984",1984
1,Bosnia and Herzegovina,Literature,,9 October 1892,13 March 1975,male,http://en.wikipedia.org/wiki/Ivo_Andric,Ivo Andric *,"Dolac (village near Travnik), Austria-Hungary ...","Belgrade, SR Serbia, SFR Yugoslavia (present-d...","Ivo Andric *, born in then Austria–Hungary ,...",1961
2,Bosnia and Herzegovina,Chemistry,,"July 23, 1906",1998-01-07,male,http://en.wikipedia.org/wiki/Vladimir_Prelog,Vladimir Prelog *,"Sarajevo , Bosnia and Herzegovina , then part...","Zürich , Switzerland","Vladimir Prelog *, born in then Austria–Hung...",1975
3,,Peace,Belgium,None,None,None,http://en.wikipedia.org/wiki/Institut_de_Droit...,Institut de Droit International,None,None,"Institut de Droit International , Peace, 1904",1904
4,,Peace,Belgium,26 July 1829,6 October 1912,male,http://en.wikipedia.org/wiki/Auguste_Marie_Fra...,Auguste Beernaert,"Ostend , Netherlands (now Belgium )","Lucerne , Switzerland","Auguste Beernaert , Peace, 1909",1909

In [7]:
data_dirty.shape

(1052, 12)

In [8]:
data_dirty.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1052 entries, 0 to 1051
Data columns (total 12 columns):
born_in           1052 non-null object
category          1052 non-null object
country           1052 non-null object
date_of_birth     1044 non-null object
date_of_death     1044 non-null object
gender            1040 non-null object
link              1052 non-null object
name              1052 non-null object
place_of_birth    1044 non-null object
place_of_death    1044 non-null object
text              1052 non-null object
year              1052 non-null int64
dtypes: int64(1), object(11)
memory usage: 98.7+ KB

In [9]:
data_dirty[data_dirty.category=='Chemistry'].country.count()

212

In [11]:
data_dirty.columns

Index(['born_in', 'category', 'country', 'date_of_birth', 'date_of_death',
       'gender', 'link', 'name', 'place_of_birth', 'place_of_death', 'text',
       'year'],
      dtype='object')

In [12]:
data_dirty = data_dirty.set_index('name')
data_dirty.head(2)
#rest 인덱스 정렬하면 인덱스가 바뀌는데 그것을 새로 정렬하는게 rest index,  drop index 하면 index 가 없어짐.

,born_in,category,country,date_of_birth,date_of_death,gender,link,place_of_birth,place_of_death,text,year
name,,,,,,,,,,,
César Milstein,,Physiology or Medicine,Argentina,8 October 1927,24 March 2002,male,http://en.wikipedia.org/wiki/C%C3%A9sar_Milstein,"Bahía Blanca , Argentina","Cambridge , England","César Milstein , Physiology or Medicine, 1984",1984
Ivo Andric *,Bosnia and Herzegovina,Literature,,9 October 1892,13 March 1975,male,http://en.wikipedia.org/wiki/Ivo_Andric,"Dolac (village near Travnik), Austria-Hungary ...","Belgrade, SR Serbia, SFR Yugoslavia (present-d...","Ivo Andric *, born in then Austria–Hungary ,...",1961

In [13]:
# set 인덱스와 reset 인덱스는 슬라이싱 할때 편하게 하려고 쓴다

In [14]:
data_dirty.iloc[0]

born_in
category                                    Physiology or Medicine
country                                                  Argentina
date_of_birth                                       8 October 1927
date_of_death                                        24 March 2002
gender                                                        male
link              http://en.wikipedia.org/wiki/C%C3%A9sar_Milstein
place_of_birth                           Bahía Blanca ,  Argentina
place_of_death                                 Cambridge , England
text                 César Milstein , Physiology or Medicine, 1984
year                                                          1984
Name: César Milstein, dtype: object

In [15]:
data_dirty.loc[0]

TypeError: cannot do label indexing on <class 'pandas.core.indexes.base.Index'> with these indexers [0] of <class 'int'>

In [17]:
#인덱스를 네임으로 만들어 버렸기때문에 안된다, iloc는 파이썬의 loc는 파이썬의 slicing 을따르고,  loc는  label 을따른다.

In [18]:
data_dirty.loc["César Milstein"]

,born_in,category,country,date_of_birth,date_of_death,gender,link,place_of_birth,place_of_death,text,year
name,,,,,,,,,,,
César Milstein,,Physiology or Medicine,Argentina,8 October 1927,24 March 2002,male,http://en.wikipedia.org/wiki/C%C3%A9sar_Milstein,"Bahía Blanca , Argentina","Cambridge , England","César Milstein , Physiology or Medicine, 1984",1984
César Milstein,,Physiology or Medicine,United Kingdom,8 October 1927,24 March 2002,male,http://en.wikipedia.org/wiki/C%C3%A9sar_Milstein,"Bahía Blanca , Argentina","Cambridge , England","César Milstein , born in Argentina , Physiolo...",1984

따라서 iloc 를 쓰는게 범용성인측면에서 더 좋다 .

set인덱스 reset 인덱스는 슬라이싱 하고 인덱싱 편하게하려고 쓴다 .

2000년도 이후에 노벨상 받은사람.

In [19]:
data_dirty.reset_index(drop = True)

bi_col = data_dirty.born_in # 중간단계를 변수에 할당한다. 

bi_col

type(bi_col)

pandas.core.series.Series

In [23]:
data_dirty.reset_index(drop = True ,inplace= True) # reset_index 에서 drop true 가 머지

In [24]:
data_dirty

,born_in,category,country,date_of_birth,date_of_death,gender,link,place_of_birth,place_of_death,text,year
0,,Physiology or Medicine,Argentina,8 October 1927,24 March 2002,male,http://en.wikipedia.org/wiki/C%C3%A9sar_Milstein,"Bahía Blanca , Argentina","Cambridge , England","César Milstein , Physiology or Medicine, 1984",1984
1,Bosnia and Herzegovina,Literature,,9 October 1892,13 March 1975,male,http://en.wikipedia.org/wiki/Ivo_Andric,"Dolac (village near Travnik), Austria-Hungary ...","Belgrade, SR Serbia, SFR Yugoslavia (present-d...","Ivo Andric *, born in then Austria–Hungary ,...",1961
2,Bosnia and Herzegovina,Chemistry,,"July 23, 1906",1998-01-07,male,http://en.wikipedia.org/wiki/Vladimir_Prelog,"Sarajevo , Bosnia and Herzegovina , then part...","Zürich , Switzerland","Vladimir Prelog *, born in then Austria–Hung...",1975
3,,Peace,Belgium,None,None,None,http://en.wikipedia.org/wiki/Institut_de_Droit...,None,None,"Institut de Droit International , Peace, 1904",1904
4,,Peace,Belgium,26 July 1829,6 October 1912,male,http://en.wikipedia.org/wiki/Auguste_Marie_Fra...,"Ostend , Netherlands (now Belgium )","Lucerne , Switzerland","Auguste Beernaert , Peace, 1909",1909
5,,Literature,Belgium,29 August 1862,6 May 1949,male,http://en.wikipedia.org/wiki/Maurice_Maeterlinck,"Ghent , Belgium","Nice , France","Maurice Maeterlinck , Literature, 1911",1911
6,,Peace,Belgium,22 April 1854,14 May 1943,male,http://en.wikipedia.org/wiki/Henri_La_Fontaine,Brussels,Belgium,"Henri La Fontaine , Peace, 1913",1913
7,,Physiology or Medicine,Belgium,13 June 1870,6 April 1961,male,http://en.wikipedia.org/wiki/Jules_Bordet,"Soignies, Belgium",,"Jules Bordet , Physiology or Medicine, 1919",1919
8,,Physiology or Medicine,Belgium,28 March 1892,18 July 1968,male,http://en.wikipedia.org/wiki/Corneille_Heymans,"Ghent , Flanders","Knokke , Flanders","Corneille Heymans , Physiology or Medicine, 1938",1938
9,,Peace,Belgium,1910-02-10,1969-01-30,male,http://en.wikipedia.org/wiki/Georges_Pire,"Dinant , Belgium","Leuven , Belgium","Georges Pire , Peace, 1958",1958
10,,Physiology or Medicine,Belgium,24 August 1899,22 May 1983,male,http://en.wikipedia.org/wiki/Albert_Claude,"Longlier, Neufchâteau, Belgium","Brussels , Belgium","Albert Claude , Physiology or Medicine, 1974",1974
11,,Physiology or Medicine,Belgium,2 October 1917,4 May 2013,male,http://en.wikipedia.org/wiki/Christian_de_Duve,"Thames Ditton, Surrey, United Kingdom","Grez-Doiceau, Belgium","Christian de Duve , born in the United Kingdo...",1974
12,,Chemistry,Belgium,25 January 1917,28 May 2003,male,http://en.wikipedia.org/wiki/Ilya_Prigogine,"Moscow , Russia","Brussels , Belgium","Ilya Prigogine , born in Russia , Chemistry, ...",1977
13,,Physics,Belgium,6 November 1932,,male,http://en.wikipedia.org/wiki/Fran%C3%A7ois_Eng...,"Etterbeek , Brussels , Belgium",,"François Englert , Physics, 2013",2013
14,Belarus,Economics,,"April 30, 1901","July 8, 1985",male,http://en.wikipedia.org/wiki/Simon_Kuznets,Pinsk,"Cambridge, Massachusetts","Simon Kuznets *, born in then Russian Empire,...",1971
15,Belarus,Peace,,16 August 1913,9 March 1992,male,http://en.wikipedia.org/wiki/Menachem_Begin,"Brest , Russian Empire","Tel Aviv , Israel","Menachem Begin *, born in then Russian Empire...",1978
16,Belarus,Peace,,2 August 1923,,male,http://en.wikipedia.org/wiki/Shimon_Peres,Poland,,"Shimon Peres *, born in then Poland, now Bela...",1994
17,,Literature,Denmark,"June 2, 1857","October 13, 1919",male,http://en.wikipedia.org/wiki/Karl_Adolph_Gjell...,"Roholte vicarage at Præstø , Denmark","Klotzsche , Germany","Karl Adolph Gjellerup , Literature, 1917",1917
18,,Physiology or Medicine,Denmark,"November 15, 1874","September 13, 1949",male,http://en.wikipedia.org/wiki/August_Krogh,,,"August Krogh , Physiology or Medicine, 1920",1920
19,,Physics,Denmark,7 October 1885,18 November 1962,male,http://en.wikipedia.org/wiki/Niels_Bohr,"Copenhagen, Denmark","Copenhagen, Denmark","Niels Bohr , Physics, 1922",1922
20,,Physiology or Medicine,Denmark,23 April 1867,30 January 1928,male,http://en.wikipedia.org/wiki/Johannes_Andreas_...,Silkeborg,Copenhagen,"Johannes Andreas Grib Fibiger , Physiology or ...",1926
21,,Physiology or Medicine,Denmark,21 February 1895,17 April 1976,male,http://en.wikipedia.org/wiki/Henrik_Dam,,,"Henrik Dam , Physiology or Medicine, 1943",1943
22,,Literature,Denmark,1873-01-20,1950-11-25,male,http://en.wikipedia.org/wiki/Johannes_Vilhelm_...,"Farsø, Jutland, Denmark","Østerbro, Copenhagen, Denmark","Johannes Vilhelm Jensen , Literature, 1944",1944
23,,Physics,Denmark,"July 9, 1926",,male,http://en.wikipedia.org/wiki/Ben_Roy_Mottelson,"Chicago, Illinois",,"Ben Roy Mottelson , Physics, 1975",1975
24,,Physics,Denmark,19 June 1922,8 September 2009,male,http://en.wikipedia.org/wiki/Aage_Bohr,"Copenhagen , Denmark","Copenhagen , Denmark","Aage Bohr , Physics, 1975",1975
25,,Physiology or Medicine,Denmark,"December 23, 1911","October 7, 1994",male,http://en.wikipedia.org/wiki/Niels_Kaj_Jerne,,,"Niels Kaj Jerne , Physiology or Medicine, 1984",1984
26,,Chemistry,Denmark,"October 8, 1918",,male,http://en.wikipedia.org/wiki/Jens_Christian_Skou,"Lemvig , Denmark",,"Jens Christian Skou , Chemistry, 1997",1997
27,Czech Republic,Peace,,"June 9, 1843","June 21, 1914",female,http://en.wikipedia.org/wiki/Bertha_von_Suttner,"Prague , Austrian Empire","Vienna , Austria-Hungary","Bertha von Suttner *, born in then Austrian-H...",1905
28,Czech Republic,Physiology or Medicine,,15 August 1896,26 October 1957,female,http://en.wikipedia.org/wiki/Gerty_Cori,"Prague , Austrian Empire",,"Gerty Cori *, born in then Austria-Hungary , ...",1947
29,Czech Republic,Physiology or Medicine,,"December 5, 1896","October 20, 1984",male,http://en.wikipedia.org/wiki/Carl_Ferdinand_Cori,Prague,"Cambridge, Massachusetts","Carl Ferdinand Cori *, born in then Austria-H...",1947
...,...,...,...,...,...,...,...,...,...,...,...
1022,,Physics,Austria,24 June 1883,17 December 1964,male,http://en.wikipedia.org/wiki/Victor_Francis_Hess,"Schloss Waldstein, Peggau , Austria","Mount Vernon, New York , USA","Victor Francis Hess , Physics, 1936",1936
1023,Austria,Physiology or Medicine,,"June 3, 1873","December 25, 1961",male,http://en.wikipedia.org/wiki/Otto_Loewi,"Frankfurt , Germany","New York City , United States","Otto Loewi *, Physiology or Medicine, 1936",1936
1024,Austria,Chemistry,,"December 3, 1900","August 1, 1967",male,http://en.wikipedia.org/wiki/Richard_Kuhn,"Vienna , Austria","Heidelberg , Germany","Richard Kuhn *, Chemistry, 1938",1938
1025,,Physics,Austria,25 April 1900,15 December 1958,male,http://en.wikipedia.org/wiki/Wolfgang_Pauli,"Vienna , Austria-Hungary","Zurich , Switzerland","Wolfgang Pauli , Physics, 1945",1945
1026,,Chemistry,Austria,19 May 1914,6 February 2002,male,http://en.wikipedia.org/wiki/Max_F._Perutz,"Vienna , Austria","Cambridge , England","Max F. Perutz , Chemistry, 1962",1962
1027,Austria,Physiology or Medicine,,1886-11-20,1982-06-12,male,http://en.wikipedia.org/wiki/Karl_von_Frisch,"Vienna, Austria","Munich , Germany","Karl von Frisch *, Physiology or Medicine, 1973",1973
1028,,Physiology or Medicine,Austria,"November 7, 1903","February 27, 1989",male,http://en.wikipedia.org/wiki/Konrad_Lorenz,"Vienna, Austria","Vienna, Austria","Konrad Lorenz , Physiology or Medicine, 1973",1973
1029,,Economics,Austria,8 May 1899,23 March 1992,male,http://en.wikipedia.org/wiki/Friedrich_Hayek,"Vienna, Austria-Hungary","Freiburg, Germany","Friedrich Hayek , Economics, 1974",1974
1030,Austria,Chemistry,,1923-03-09,,male,http://en.wikipedia.org/wiki/Walter_Kohn,Vienna,,"Walter Kohn *, Chemistry, 1998",1998
1031,Austria,Physiology or Medicine,,7 November 1929,,male,http://en.wikipedia.org/wiki/Eric_R._Kandel,"Vienna , Austria",,"Eric R. Kandel *, Physiology or Medicine, 2000",2000
1032,,Literature,Austria,20 October 1946,,female,http://en.wikipedia.org/wiki/Elfriede_Jelinek,"Mürzzuschlag , Styria , Austria",,"Elfriede Jelinek , Literature, 2004",2004
1033,,Peace,Austria,None,None,None,http://en.wikipedia.org/wiki/International_Ato...,None,None,"International Atomic Energy Agency , Peace, 2005",2005
1034,Austria,Chemistry,,"March 15, 1930",,male,http://en.wikipedia.org/wiki/Martin_Karplus,"Vienna , Austria",,"Martin Karplus *, Chemistry, 2013",2013
1035,Australia,Physics,,31 March 1890,1 July 1971,male,http://en.wikipedia.org/wiki/William_Lawrence_...,"North Adelaide , South Australia","Waldringfield , Suffolk, England","William Lawrence Bragg *, Physics, 1915",1915
1036,,Physiology or Medicine,Australia,24 September 1898,21 February 1968,male,http://en.wikipedia.org/wiki/Howard_Walter_Florey,"Adelaide , South Australia","Oxford , United Kingdom","Sir Howard Florey , Physiology or Medicine, 1945",1945
1037,,Physiology or Medicine,Australia,3 September 1899,31 August 1985,male,http://en.wikipedia.org/wiki/Frank_Macfarlane_...,"Traralgon, Victoria","Port Fairy, Victoria","Sir Frank Macfarlane Burnet , Physiology or Me...",1960
1038,,Physiology or Medicine,Australia,27 January 1903,2 May 1997,male,http://en.wikipedia.org/wiki/John_Carew_Eccles,"Melbourne , Australia","Tenero-Contra , Switzerland","John Carew Eccles , Physiology or Medicine, 1963",1963
1039,Australia,Physics,,11 July 1916,8 January 2002,male,http://en.wikipedia.org/wiki/Aleksandr_M._Prok...,"Atherton, Queensland , Australia","Moscow , Russia","Aleksandr M. Prokhorov *, Physics, 1964",1964
1040,,Literature,Australia,28 May 1912,30 September 1990,male,http://en.wikipedia.org/wiki/Patrick_White,"Knightsbridge , London","Sydney, Australia","Patrick White , born in the United Kingdom , ...",1973
1041,Australia,Chemistry,,7 September 1917,8 December 2013,male,http://en.wikipedia.org/wiki/John_Warcup_Cornf...,"Sydney , Australia",England,"John Warcup Cornforth *, Chemistry, 1975",1975
1042,,Economics,Australia,"May 29, 1920","August 9, 2000",male,http://en.wikipedia.org/wiki/John_Harsanyi,"Budapest , Hungary","Berkeley, California , USA","John Harsanyi , Economics, 1994",1994
1043,,Physiology or Medicine,Australia,15 October 1940,,male,http://en.wikipedia.org/wiki/Peter_C._Doherty,Brisbane,,Peter C. Doherty & Professor Rolf Zinkernage...,1996
1044,,Physiology or Medicine,Australia,11 June 1937,,male,http://en.wikipedia.org/wiki/Robin_Warren,"Adelaide , Australia",,"J. Robin Warren , Physiology or Medicine, 2005",2005
1045,,Physiology or Medicine,Australia,30 September 1951,,male,http://en.wikipedia.org/wiki/Barry_Marshall,"Kalgoorlie, Western Australia",,"Barry Marshall , Physiology or Medicine, 2005",2005
1046,Australia,Physiology or Medicine,,1948-11-26,,female,http://en.wikipedia.org/wiki/Elizabeth_H._Blac...,"Hobart , Tasmania , Australia",,"Elizabeth H. Blackburn *, Physiology or Medici...",2009
1047,,Physics,Australia,"February 24, 1967",,male,http://en.wikipedia.org/wiki/Brian_P._Schmidt,"Missoula, Montana",,"Brian P. Schmidt , born in the United States ...",2011
1048,,Peace,Argentina,"November 1, 1878","May 5, 1959",male,http://en.wikipedia.org/wiki/Carlos_Saavedra_L...,"Buenos Aires , Argentina","Buenos Aires, Argentina","Carlos Saavedra Lamas , Peace, 1936",1936
1049,,Physiology or Medicine,Argentina,1887-04-10,1971-09-21,male,http://en.wikipedia.org/wiki/Bernardo_Houssay,"Buenos Aires , Argentina","Buenos Aires , Argentina","Bernardo Houssay , Physiology or Medicine, 1947",1947
1050,,Chemistry,Argentina,1906-9-6,1987-12-2,male,http://en.wikipedia.org/wiki/Luis_Federico_Leloir,"Paris , France","Buenos Aires , Argentina","Luis Federico Leloir , Chemistry, 1970",1970
1051,,Peace,Argentina,"November 26, 1931",,male,http://en.wikipedia.org/wiki/Adolfo_P%C3%A9rez...,Buenos Aires,,"Adolfo Pérez Esquivel , Peace, 1980",1980

In [25]:
data_dirty[data_dirty.year > 2000]

,born_in,category,country,date_of_birth,date_of_death,gender,link,place_of_birth,place_of_death,text,year
13,,Physics,Belgium,6 November 1932,,male,http://en.wikipedia.org/wiki/Fran%C3%A7ois_Eng...,"Etterbeek , Brussels , Belgium",,"François Englert , Physics, 2013",2013
32,,Economics,Cyprus,1948-02-20,,male,http://en.wikipedia.org/wiki/Christopher_A._Pi...,"Nicosia, Cyprus",,"Christopher A. Pissarides , Economics, 2010",2010
66,,Peace,Ghana,8 April 1938,,male,http://en.wikipedia.org/wiki/Kofi_Annan,"Kumasi , Ghana",,"Kofi Annan , Peace, 2001",2001
87,Italy,Physics,,"October 6, 1931",,male,http://en.wikipedia.org/wiki/Riccardo_Giacconi,"Genoa , Italy",,"Riccardo Giacconi *, Physics, 2002",2002
88,Italy,Physiology or Medicine,,6 October 1937,,male,http://en.wikipedia.org/wiki/Mario_Capecchi,"Verona , Italy",,"Mario Capecchi *, Physiology or Medicine, 2007",2007
93,,Economics,Israel,"March 5, 1934",,male,http://en.wikipedia.org/wiki/Daniel_Kahneman,"Tel Aviv, Israel",,"Daniel Kahneman , Economics, 2002",2002
94,,Chemistry,Israel,"December 31, 1937",,male,http://en.wikipedia.org/wiki/Avram_Hershko,"Karcag, Hungary",,"Avram Hershko , born in Hungary , Chemistry, ...",2004
95,,Chemistry,Israel,"October 1, 1947",,male,http://en.wikipedia.org/wiki/Aaron_Ciechanover,"Haifa, Mandatory Palestine",,"Aaron Ciechanover , Chemistry, 2004",2004
96,,Economics,Israel,"June 8, 1930",,male,http://en.wikipedia.org/wiki/Robert_Aumann,"Frankfurt am Main , Germany",,"Robert Aumann , born in Germany , Economics, ...",2005
97,,Physics,Netherlands,1 October 1958,,male,http://en.wikipedia.org/wiki/Andre_Geim,"Sochi , Russia",,"Andre Geim , born in Russia , Physics, 2010",2010
103,Luxembourg,Physiology or Medicine,,2 August 1941,,male,http://en.wikipedia.org/wiki/Jules_A._Hoffmann,Echternach,,"Jules A. Hoffmann *, Physiology or Medicine, 2011",2011
107,,Peace,Liberia,1 February 1972,,female,http://en.wikipedia.org/wiki/Leymah_Gbowee,Central Liberia,,"Leymah Gbowee , Peace, 2011",2011
108,,Peace,Liberia,29 October 1938,,female,http://en.wikipedia.org/wiki/Ellen_Johnson_Sir...,"Monrovia , Liberia",,"Ellen Johnson Sirleaf , Peace, 2011",2011
112,,Peace,Kenya,1 April 1940,25 September 2011,female,http://en.wikipedia.org/wiki/Wangari_Muta_Maathai,"Ihithe village, Nyeri District , Kenya","Nairobi, Kenya","Wangari Muta Maathai , Peace, 2004",2004
126,South Africa,Physiology or Medicine,,13 January 1927,,male,http://en.wikipedia.org/wiki/Sydney_Brenner,"Germiston, Gauteng , South Africa",,"Sydney Brenner *, Physiology or Medicine, 2002",2002
127,,Literature,South Africa,9 February 1940,,male,http://en.wikipedia.org/wiki/J._M._Coetzee,"Cape Town, South Africa",,"J. M. Coetzee , Literature, 2003",2003
128,South Africa,Chemistry,,9 May 1947,,male,http://en.wikipedia.org/wiki/Michael_Levitt,"Pretoria, South Africa",,"Michael Levitt *, Chemistry, 2013",2013
161,,Physics,United States,"December 16, 1969",,male,http://en.wikipedia.org/wiki/Adam_G._Riess,"Washington, D.C., United States",,"Adam G. Riess , Physics, 2011",2011
162,,Physics,United States,"February 24, 1967",,male,http://en.wikipedia.org/wiki/Brian_P._Schmidt,"Missoula, Montana",,"Brian P. Schmidt , Physics, 2011",2011
163,,Physics,United States,1959-09-22,,male,http://en.wikipedia.org/wiki/Saul_Perlmutter,"Champaign-Urbana , Illinois , U.S.",,"Saul Perlmutter , Physics, 2011",2011
164,,Economics,United States,"July 19, 1943",,male,http://en.wikipedia.org/wiki/Thomas_J._Sargent,"Pasadena, California",,"Thomas J. Sargent , Economics, 2011",2011
165,,Economics,United States,"October 21, 1942",,male,http://en.wikipedia.org/wiki/Christopher_A._Sims,"Washington, D.C.",,"Christopher A. Sims , Economics, 2011",2011
166,,Physics,United States,"February 24, 1944",,male,http://en.wikipedia.org/wiki/David_J._Wineland,"Milwaukee, Wisconsin, USA",,"David J. Wineland , Physics, 2012",2012
167,,Chemistry,United States,1943-04-15,,male,http://en.wikipedia.org/wiki/Robert_J._Lefkowitz,"Bronx, New York , United States",,"Robert J. Lefkowitz , Chemistry, 2012",2012
168,,Chemistry,United States,1955-05-30,,male,http://en.wikipedia.org/wiki/Brian_Kobilka,"Little Falls, Minnesota , USA",,"Brian K. Kobilka , Chemistry, 2012",2012
169,,Economics,United States,"June 2, 1923",,male,http://en.wikipedia.org/wiki/Lloyd_S._Shapley,"Cambridge, Massachusetts",,"Lloyd S. Shapley , Economics, 2012",2012
170,,Economics,United States,1951-12-19,,male,http://en.wikipedia.org/wiki/Alvin_E._Roth,New York City,,"Alvin E. Roth , Economics, 2012",2012
171,,Physiology or Medicine,United States,"November 3, 1950",,male,http://en.wikipedia.org/wiki/James_Rothman,"Haverhill, Massachusetts",,"James Rothman , Physiology or Medicine, 2013",2013
172,,Physiology or Medicine,United States,"December 22, 1955",,male,http://en.wikipedia.org/wiki/Thomas_C._S%C3%BC...,"Göttingen, Germany",,"Thomas C. Südhof , born in Germany , Physiolo...",2013
173,,Physiology or Medicine,United States,1948-12-30,,male,http://en.wikipedia.org/wiki/Randy_Schekman,"Saint Paul, Minnesota, USA",,"Randy Schekman , Physiology or Medicine, 2013",2013
...,...,...,...,...,...,...,...,...,...,...,...
903,,Physiology or Medicine,Germany,11 March 1936,,male,http://en.wikipedia.org/wiki/Harald_zur_Hausen,"Gelsenkirchen , Germany",,"Harald zur Hausen , Physiology or Medicine, 2008",2008
904,,Literature,Germany,17 August 1953,,female,http://en.wikipedia.org/wiki/Herta_M%C3%BCller,"Nițchidorf , Timiș County , Romania",,"Herta Müller , born in Romania , Literature, ...",2009
905,,Physiology or Medicine,Germany,"December 22, 1955",,male,http://en.wikipedia.org/wiki/Thomas_C._S%C3%BC...,"Göttingen, Germany",,"Thomas C. Südhof , Physiology or Medicine, 2013",2013
906,,Chemistry,Germany,"December 23, 1962",,male,http://en.wikipedia.org/wiki/Stefan_Hell,"Arad , Romania",,"Stefan Hell , born in Romania , Chemistry, 2014",2014
949,,Chemistry,France,"October 10, 1930",,male,http://en.wikipedia.org/wiki/Yves_Chauvin,,,"Yves Chauvin , Chemistry, 2005",2005
950,,Physics,France,1938-03-07,,male,http://en.wikipedia.org/wiki/Albert_Fert,"Carcassonne , France",,"Albert Fert , Physics, 2007",2007
951,,Physiology or Medicine,France,30 July 1947,,female,http://en.wikipedia.org/wiki/Fran%C3%A7oise_Ba...,"Paris , France",,"Françoise Barré-Sinoussi , Physiology or Medic...",2008
952,,Physiology or Medicine,France,18 August 1932,,male,http://en.wikipedia.org/wiki/Luc_Montagnier,"Chabris , France",,"Luc Montagnier , Physiology or Medicine, 2008",2008
953,,Literature,France,13 April 1940,,male,http://en.wikipedia.org/wiki/J._M._G._Le_Cl%C3...,"Nice, France",,"J. M. G. Le Clézio , Literature, 2008",2008
954,,Physiology or Medicine,France,2 August 1941,,male,http://en.wikipedia.org/wiki/Jules_A._Hoffmann,Echternach,,"Jules A. Hoffmann , born in Luxembourg , Phys...",2011
955,,Physics,France,11 September 1944,,male,http://en.wikipedia.org/wiki/Serge_Haroche,"Casablanca , Morocco (then a French protect...",,"Serge Haroche , born in Morocco, then under F...",2012
956,,Literature,France,30 July 1945,,male,http://en.wikipedia.org/wiki/Patrick_Modiano,"Boulogne-Billancourt , France",,"Patrick Modiano , Literature, 2014",2014
957,,Economics,France,"August 9, 1953",,male,http://en.wikipedia.org/wiki/Jean_Tirole,Troyes,,"Jean Tirole , Economics, 2014",2014
961,,Peace,Finland,23 June 1937,,male,http://en.wikipedia.org/wiki/Martti_Ahtisaari,"Viipuri , Finland (now Vyborg, Russia)",,"Martti Ahtisaari , Peace, 2008",2008
966,,Peace,Egypt,17 June 1942,,male,http://en.wikipedia.org/wiki/Mohamed_ElBaradei,"Cairo , Egypt",,"Mohamed ElBaradei , Peace, 2005",2005
980,China,Physics,,1933-11-04,,male,http://en.wikipedia.org/wiki/Charles_K._Kao,"Shanghai, China",,"Charles K. Kao *, Physics, 2009",2009
981,,Peace,China,1955-12-28,,male,http://en.wikipedia.org/wiki/Liu_Xiaobo,"Changchun , Jilin, China",,"Liu Xiaobo , Peace, 2010",2010
982,,Literature,China,17 February 1955,,male,http://en.wikipedia.org/wiki/Mo_Yan,"Gaomi , Shandong , China",,"Mo Yan , Literature, 2012",2012
1004,,Physiology or Medicine,Canada,"November 9, 1952",,male,http://en.wikipedia.org/wiki/Jack_W._Szostak,"London , United Kingdom",,"Jack W. Szostak , born in the United Kingdom ...",2009
1005,Canada,Physics,,"August 19, 1924","May 7, 2011",male,http://en.wikipedia.org/wiki/Willard_S._Boyle,"Amherst , Nova Scotia , Canada","Wallace , Nova Scotia , Canada","Willard S. Boyle *, Physics, 2009",2009
1006,,Physiology or Medicine,Canada,"January 14, 1943","September 30, 2011",male,http://en.wikipedia.org/wiki/Ralph_M._Steinman,"Montreal, Quebec, Canada","New York City, New York, U.S.","Ralph M. Steinman , Physiology or Medicine, 2011",2011
1007,,Literature,Canada,1931-07-10,,female,http://en.wikipedia.org/wiki/Alice_Munro,"Wingham, Ontario , Canada",,"Alice Munro , Literature, 2013",2013
1011,,Peace,Bangladesh,28 June 1940,,male,http://en.wikipedia.org/wiki/Muhammad_Yunus,"Chittagong , British India",,"Muhammad Yunus , Peace, 2006",2006
1032,,Literature,Austria,20 October 1946,,female,http://en.wikipedia.org/wiki/Elfriede_Jelinek,"Mürzzuschlag , Styria , Austria",,"Elfriede Jelinek , Literature, 2004",2004
1033,,Peace,Austria,None,None,None,http://en.wikipedia.org/wiki/International_Ato...,None,None,"International Atomic Energy Agency , Peace, 2005",2005
1034,Austria,Chemistry,,"March 15, 1930",,male,http://en.wikipedia.org/wiki/Martin_Karplus,"Vienna , Austria",,"Martin Karplus *, Chemistry, 2013",2013
1044,,Physiology or Medicine,Australia,11 June 1937,,male,http://en.wikipedia.org/wiki/Robin_Warren,"Adelaide , Australia",,"J. Robin Warren , Physiology or Medicine, 2005",2005
1045,,Physiology or Medicine,Australia,30 September 1951,,male,http://en.wikipedia.org/wiki/Barry_Marshall,"Kalgoorlie, Western Australia",,"Barry Marshall , Physiology or Medicine, 2005",2005
1046,Australia,Physiology or Medicine,,1948-11-26,,female,http://en.wikipedia.org/wiki/Elizabeth_H._Blac...,"Hobart , Tasmania , Australia",,"Elizabeth H. Blackburn *, Physiology or Medici...",2009
1047,,Physics,Australia,"February 24, 1967",,male,http://en.wikipedia.org/wiki/Brian_P._Schmidt,"Missoula, Montana",,"Brian P. Schmidt , born in the United States ...",2011

In [26]:
data_dirty[data_dirty.year > 2000].count()

born_in           202
category          202
country           202
date_of_birth     201
date_of_death     201
gender            200
link              202
place_of_birth    201
place_of_death    201
text              202
year              202
dtype: int64

In [27]:
data_dirty.born_in #시리즈  태어난 장소가 비어있는게 있다 정보가없어서 .

0
1       Bosnia and Herzegovina
2       Bosnia and Herzegovina
3
4
5
6
7
8
9
10
11
12
13
14                     Belarus
15                     Belarus
16                     Belarus
17
18
19
20
21
22
23
24
25
26
27              Czech Republic
28              Czech Republic
29              Czech Republic
                 ...
1022
1023                   Austria
1024                   Austria
1025
1026
1027                   Austria
1028
1029
1030                   Austria
1031                   Austria
1032
1033
1034                   Austria
1035                 Australia
1036
1037
1038
1039                 Australia
1040
1041                 Australia
1042
1043
1044
1045
1046                 Australia
1047
1048
1049
1050
1051
Name: born_in, Length: 1052, dtype: object

In [28]:
set(data_dirty.born_in.apply(type))  # 시리즈에 apply 는, 어플라이는 functional 패러다임이라서 인자가 함수명이온다. row 별로 하나씩 함수를 적용

{str}

In [29]:
data_dirty.born_in.apply(len) #함수형 패러다임 . : 함수만 집어넣으면 전체 가 쫙 다나온다.

0        0
1       22
2       22
3        0
4        0
5        0
6        0
7        0
8        0
9        0
10       0
11       0
12       0
13       0
14       7
15       7
16       7
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27      14
28      14
29      14
        ..
1022     0
1023     7
1024     7
1025     0
1026     0
1027     7
1028     0
1029     0
1030     7
1031     7
1032     0
1033     0
1034     7
1035     9
1036     0
1037     0
1038     0
1039     9
1040     0
1041     9
1042     0
1043     0
1044     0
1045     0
1046     9
1047     0
1048     0
1049     0
1050     0
1051     0
Name: born_in, Length: 1052, dtype: int64

In [30]:
data_dirty.born_in.map(lambda x:len(x)) # map 은 시리즈에서만 쓸수있다. 반면에 apply 는 series 도 되고 dataframe 에서도 됨.

0        0
1       22
2       22
3        0
4        0
5        0
6        0
7        0
8        0
9        0
10       0
11       0
12       0
13       0
14       7
15       7
16       7
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27      14
28      14
29      14
        ..
1022     0
1023     7
1024     7
1025     0
1026     0
1027     7
1028     0
1029     0
1030     7
1031     7
1032     0
1033     0
1034     7
1035     9
1036     0
1037     0
1038     0
1039     9
1040     0
1041     9
1042     0
1043     0
1044     0
1045     0
1046     9
1047     0
1048     0
1049     0
1050     0
1051     0
Name: born_in, Length: 1052, dtype: int64

In [32]:
#data_dirty.born_in.map(len) 이것도 됨

In [33]:
# 0 인부분을 unknown 으로 바꾸기위해서 새로운 함수를 정의

In [34]:
def unkown(x):
    if not len(x):
        return 'unknown'
    else:
        return x
data_dirty.born_in.map(unkown) # map에는 inplace 가 없으니까 .

data_dirty.born_in =data_dirty.born_in.map(unkown)  # 기존에 있는것을 새롭게 할당

In [35]:
data_dirty

,born_in,category,country,date_of_birth,date_of_death,gender,link,place_of_birth,place_of_death,text,year
0,unknown,Physiology or Medicine,Argentina,8 October 1927,24 March 2002,male,http://en.wikipedia.org/wiki/C%C3%A9sar_Milstein,"Bahía Blanca , Argentina","Cambridge , England","César Milstein , Physiology or Medicine, 1984",1984
1,Bosnia and Herzegovina,Literature,,9 October 1892,13 March 1975,male,http://en.wikipedia.org/wiki/Ivo_Andric,"Dolac (village near Travnik), Austria-Hungary ...","Belgrade, SR Serbia, SFR Yugoslavia (present-d...","Ivo Andric *, born in then Austria–Hungary ,...",1961
2,Bosnia and Herzegovina,Chemistry,,"July 23, 1906",1998-01-07,male,http://en.wikipedia.org/wiki/Vladimir_Prelog,"Sarajevo , Bosnia and Herzegovina , then part...","Zürich , Switzerland","Vladimir Prelog *, born in then Austria–Hung...",1975
3,unknown,Peace,Belgium,None,None,None,http://en.wikipedia.org/wiki/Institut_de_Droit...,None,None,"Institut de Droit International , Peace, 1904",1904
4,unknown,Peace,Belgium,26 July 1829,6 October 1912,male,http://en.wikipedia.org/wiki/Auguste_Marie_Fra...,"Ostend , Netherlands (now Belgium )","Lucerne , Switzerland","Auguste Beernaert , Peace, 1909",1909
5,unknown,Literature,Belgium,29 August 1862,6 May 1949,male,http://en.wikipedia.org/wiki/Maurice_Maeterlinck,"Ghent , Belgium","Nice , France","Maurice Maeterlinck , Literature, 1911",1911
6,unknown,Peace,Belgium,22 April 1854,14 May 1943,male,http://en.wikipedia.org/wiki/Henri_La_Fontaine,Brussels,Belgium,"Henri La Fontaine , Peace, 1913",1913
7,unknown,Physiology or Medicine,Belgium,13 June 1870,6 April 1961,male,http://en.wikipedia.org/wiki/Jules_Bordet,"Soignies, Belgium",,"Jules Bordet , Physiology or Medicine, 1919",1919
8,unknown,Physiology or Medicine,Belgium,28 March 1892,18 July 1968,male,http://en.wikipedia.org/wiki/Corneille_Heymans,"Ghent , Flanders","Knokke , Flanders","Corneille Heymans , Physiology or Medicine, 1938",1938
9,unknown,Peace,Belgium,1910-02-10,1969-01-30,male,http://en.wikipedia.org/wiki/Georges_Pire,"Dinant , Belgium","Leuven , Belgium","Georges Pire , Peace, 1958",1958
10,unknown,Physiology or Medicine,Belgium,24 August 1899,22 May 1983,male,http://en.wikipedia.org/wiki/Albert_Claude,"Longlier, Neufchâteau, Belgium","Brussels , Belgium","Albert Claude , Physiology or Medicine, 1974",1974
11,unknown,Physiology or Medicine,Belgium,2 October 1917,4 May 2013,male,http://en.wikipedia.org/wiki/Christian_de_Duve,"Thames Ditton, Surrey, United Kingdom","Grez-Doiceau, Belgium","Christian de Duve , born in the United Kingdo...",1974
12,unknown,Chemistry,Belgium,25 January 1917,28 May 2003,male,http://en.wikipedia.org/wiki/Ilya_Prigogine,"Moscow , Russia","Brussels , Belgium","Ilya Prigogine , born in Russia , Chemistry, ...",1977
13,unknown,Physics,Belgium,6 November 1932,,male,http://en.wikipedia.org/wiki/Fran%C3%A7ois_Eng...,"Etterbeek , Brussels , Belgium",,"François Englert , Physics, 2013",2013
14,Belarus,Economics,,"April 30, 1901","July 8, 1985",male,http://en.wikipedia.org/wiki/Simon_Kuznets,Pinsk,"Cambridge, Massachusetts","Simon Kuznets *, born in then Russian Empire,...",1971
15,Belarus,Peace,,16 August 1913,9 March 1992,male,http://en.wikipedia.org/wiki/Menachem_Begin,"Brest , Russian Empire","Tel Aviv , Israel","Menachem Begin *, born in then Russian Empire...",1978
16,Belarus,Peace,,2 August 1923,,male,http://en.wikipedia.org/wiki/Shimon_Peres,Poland,,"Shimon Peres *, born in then Poland, now Bela...",1994
17,unknown,Literature,Denmark,"June 2, 1857","October 13, 1919",male,http://en.wikipedia.org/wiki/Karl_Adolph_Gjell...,"Roholte vicarage at Præstø , Denmark","Klotzsche , Germany","Karl Adolph Gjellerup , Literature, 1917",1917
18,unknown,Physiology or Medicine,Denmark,"November 15, 1874","September 13, 1949",male,http://en.wikipedia.org/wiki/August_Krogh,,,"August Krogh , Physiology or Medicine, 1920",1920
19,unknown,Physics,Denmark,7 October 1885,18 November 1962,male,http://en.wikipedia.org/wiki/Niels_Bohr,"Copenhagen, Denmark","Copenhagen, Denmark","Niels Bohr , Physics, 1922",1922
20,unknown,Physiology or Medicine,Denmark,23 April 1867,30 January 1928,male,http://en.wikipedia.org/wiki/Johannes_Andreas_...,Silkeborg,Copenhagen,"Johannes Andreas Grib Fibiger , Physiology or ...",1926
21,unknown,Physiology or Medicine,Denmark,21 February 1895,17 April 1976,male,http://en.wikipedia.org/wiki/Henrik_Dam,,,"Henrik Dam , Physiology or Medicine, 1943",1943
22,unknown,Literature,Denmark,1873-01-20,1950-11-25,male,http://en.wikipedia.org/wiki/Johannes_Vilhelm_...,"Farsø, Jutland, Denmark","Østerbro, Copenhagen, Denmark","Johannes Vilhelm Jensen , Literature, 1944",1944
23,unknown,Physics,Denmark,"July 9, 1926",,male,http://en.wikipedia.org/wiki/Ben_Roy_Mottelson,"Chicago, Illinois",,"Ben Roy Mottelson , Physics, 1975",1975
24,unknown,Physics,Denmark,19 June 1922,8 September 2009,male,http://en.wikipedia.org/wiki/Aage_Bohr,"Copenhagen , Denmark","Copenhagen , Denmark","Aage Bohr , Physics, 1975",1975
25,unknown,Physiology or Medicine,Denmark,"December 23, 1911","October 7, 1994",male,http://en.wikipedia.org/wiki/Niels_Kaj_Jerne,,,"Niels Kaj Jerne , Physiology or Medicine, 1984",1984
26,unknown,Chemistry,Denmark,"October 8, 1918",,male,http://en.wikipedia.org/wiki/Jens_Christian_Skou,"Lemvig , Denmark",,"Jens Christian Skou , Chemistry, 1997",1997
27,Czech Republic,Peace,,"June 9, 1843","June 21, 1914",female,http://en.wikipedia.org/wiki/Bertha_von_Suttner,"Prague , Austrian Empire","Vienna , Austria-Hungary","Bertha von Suttner *, born in then Austrian-H...",1905
28,Czech Republic,Physiology or Medicine,,15 August 1896,26 October 1957,female,http://en.wikipedia.org/wiki/Gerty_Cori,"Prague , Austrian Empire",,"Gerty Cori *, born in then Austria-Hungary , ...",1947
29,Czech Republic,Physiology or Medicine,,"December 5, 1896","October 20, 1984",male,http://en.wikipedia.org/wiki/Carl_Ferdinand_Cori,Prague,"Cambridge, Massachusetts","Carl Ferdinand Cori *, born in then Austria-H...",1947
...,...,...,...,...,...,...,...,...,...,...,...
1022,unknown,Physics,Austria,24 June 1883,17 December 1964,male,http://en.wikipedia.org/wiki/Victor_Francis_Hess,"Schloss Waldstein, Peggau , Austria","Mount Vernon, New York , USA","Victor Francis Hess , Physics, 1936",1936
1023,Austria,Physiology or Medicine,,"June 3, 1873","December 25, 1961",male,http://en.wikipedia.org/wiki/Otto_Loewi,"Frankfurt , Germany","New York City , United States","Otto Loewi *, Physiology or Medicine, 1936",1936
1024,Austria,Chemistry,,"December 3, 1900","August 1, 1967",male,http://en.wikipedia.org/wiki/Richard_Kuhn,"Vienna , Austria","Heidelberg , Germany","Richard Kuhn *, Chemistry, 1938",1938
1025,unknown,Physics,Austria,25 April 1900,15 December 1958,male,http://en.wikipedia.org/wiki/Wolfgang_Pauli,"Vienna , Austria-Hungary","Zurich , Switzerland","Wolfgang Pauli , Physics, 1945",1945
1026,unknown,Chemistry,Austria,19 May 1914,6 February 2002,male,http://en.wikipedia.org/wiki/Max_F._Perutz,"Vienna , Austria","Cambridge , England","Max F. Perutz , Chemistry, 1962",1962
1027,Austria,Physiology or Medicine,,1886-11-20,1982-06-12,male,http://en.wikipedia.org/wiki/Karl_von_Frisch,"Vienna, Austria","Munich , Germany","Karl von Frisch *, Physiology or Medicine, 1973",1973
1028,unknown,Physiology or Medicine,Austria,"November 7, 1903","February 27, 1989",male,http://en.wikipedia.org/wiki/Konrad_Lorenz,"Vienna, Austria","Vienna, Austria","Konrad Lorenz , Physiology or Medicine, 1973",1973
1029,unknown,Economics,Austria,8 May 1899,23 March 1992,male,http://en.wikipedia.org/wiki/Friedrich_Hayek,"Vienna, Austria-Hungary","Freiburg, Germany","Friedrich Hayek , Economics, 1974",1974
1030,Austria,Chemistry,,1923-03-09,,male,http://en.wikipedia.org/wiki/Walter_Kohn,Vienna,,"Walter Kohn *, Chemistry, 1998",1998
1031,Austria,Physiology or Medicine,,7 November 1929,,male,http://en.wikipedia.org/wiki/Eric_R._Kandel,"Vienna , Austria",,"Eric R. Kandel *, Physiology or Medicine, 2000",2000
1032,unknown,Literature,Austria,20 October 1946,,female,http://en.wikipedia.org/wiki/Elfriede_Jelinek,"Mürzzuschlag , Styria , Austria",,"Elfriede Jelinek , Literature, 2004",2004
1033,unknown,Peace,Austria,None,None,None,http://en.wikipedia.org/wiki/International_Ato...,None,None,"International Atomic Energy Agency , Peace, 2005",2005
1034,Austria,Chemistry,,"March 15, 1930",,male,http://en.wikipedia.org/wiki/Martin_Karplus,"Vienna , Austria",,"Martin Karplus *, Chemistry, 2013",2013
1035,Australia,Physics,,31 March 1890,1 July 1971,male,http://en.wikipedia.org/wiki/William_Lawrence_...,"North Adelaide , South Australia","Waldringfield , Suffolk, England","William Lawrence Bragg *, Physics, 1915",1915
1036,unknown,Physiology or Medicine,Australia,24 September 1898,21 February 1968,male,http://en.wikipedia.org/wiki/Howard_Walter_Florey,"Adelaide , South Australia","Oxford , United Kingdom","Sir Howard Florey , Physiology or Medicine, 1945",1945
1037,unknown,Physiology or Medicine,Australia,3 September 1899,31 August 1985,male,http://en.wikipedia.org/wiki/Frank_Macfarlane_...,"Traralgon, Victoria","Port Fairy, Victoria","Sir Frank Macfarlane Burnet , Physiology or Me...",1960
1038,unknown,Physiology or Medicine,Australia,27 January 1903,2 May 1997,male,http://en.wikipedia.org/wiki/John_Carew_Eccles,"Melbourne , Australia","Tenero-Contra , Switzerland","John Carew Eccles , Physiology or Medicine, 1963",1963
1039,Australia,Physics,,11 July 1916,8 January 2002,male,http://en.wikipedia.org/wiki/Aleksandr_M._Prok...,"Atherton, Queensland , Australia","Moscow , Russia","Aleksandr M. Prokhorov *, Physics, 1964",1964
1040,unknown,Literature,Australia,28 May 1912,30 September 1990,male,http://en.wikipedia.org/wiki/Patrick_White,"Knightsbridge , London","Sydney, Australia","Patrick White , born in the United Kingdom , ...",1973
1041,Australia,Chemistry,,7 September 1917,8 December 2013,male,http://en.wikipedia.org/wiki/John_Warcup_Cornf...,"Sydney , Australia",England,"John Warcup Cornforth *, Chemistry, 1975",1975
1042,unknown,Economics,Australia,"May 29, 1920","August 9, 2000",male,http://en.wikipedia.org/wiki/John_Harsanyi,"Budapest , Hungary","Berkeley, California , USA","John Harsanyi , Economics, 1994",1994
1043,unknown,Physiology or Medicine,Australia,15 October 1940,,male,http://en.wikipedia.org/wiki/Peter_C._Doherty,Brisbane,,Peter C. Doherty & Professor Rolf Zinkernage...,1996
1044,unknown,Physiology or Medicine,Australia,11 June 1937,,male,http://en.wikipedia.org/wiki/Robin_Warren,"Adelaide , Australia",,"J. Robin Warren , Physiology or Medicine, 2005",2005
1045,unknown,Physiology or Medicine,Australia,30 September 1951,,male,http://en.wikipedia.org/wiki/Barry_Marshall,"Kalgoorlie, Western Australia",,"Barry Marshall , Physiology or Medicine, 2005",2005
1046,Australia,Physiology or Medicine,,1948-11-26,,female,http://en.wikipedia.org/wiki/Elizabeth_H._Blac...,"Hobart , Tasmania , Australia",,"Elizabeth H. Blackburn *, Physiology or Medici...",2009
1047,unknown,Physics,Australia,"February 24, 1967",,male,http://en.wikipedia.org/wiki/Brian_P._Schmidt,"Missoula, Montana",,"Brian P. Schmidt , born in the United States ...",2011
1048,unknown,Peace,Argentina,"November 1, 1878","May 5, 1959",male,http://en.wikipedia.org/wiki/Carlos_Saavedra_L...,"Buenos Aires , Argentina","Buenos Aires, Argentina","Carlos Saavedra Lamas , Peace, 1936",1936
1049,unknown,Physiology or Medicine,Argentina,1887-04-10,1971-09-21,male,http://en.wikipedia.org/wiki/Bernardo_Houssay,"Buenos Aires , Argentina","Buenos Aires , Argentina","Bernardo Houssay , Physiology or Medicine, 1947",1947
1050,unknown,Chemistry,Argentina,1906-9-6,1987-12-2,male,http://en.wikipedia.org/wiki/Luis_Federico_Leloir,"Paris , France","Buenos Aires , Argentina","Luis Federico Leloir , Chemistry, 1970",1970
1051,unknown,Peace,Argentina,"November 26, 1931",,male,http://en.wikipedia.org/wiki/Adolfo_P%C3%A9rez...,Buenos Aires,,"Adolfo Pérez Esquivel , Peace, 1980",1980

In [36]:
data_dirty.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1052 entries, 0 to 1051
Data columns (total 11 columns):
born_in           1052 non-null object
category          1052 non-null object
country           1052 non-null object
date_of_birth     1044 non-null object
date_of_death     1044 non-null object
gender            1040 non-null object
link              1052 non-null object
place_of_birth    1044 non-null object
place_of_death    1044 non-null object
text              1052 non-null object
year              1052 non-null int64
dtypes: int64(1), object(10)
memory usage: 90.5+ KB

In [37]:
#비어있는 데이터를 unkown 으로 대체함.

In [38]:
bi_col  = data_dirty.born_in

In [39]:
bi_col

0                      unknown
1       Bosnia and Herzegovina
2       Bosnia and Herzegovina
3                      unknown
4                      unknown
5                      unknown
6                      unknown
7                      unknown
8                      unknown
9                      unknown
10                     unknown
11                     unknown
12                     unknown
13                     unknown
14                     Belarus
15                     Belarus
16                     Belarus
17                     unknown
18                     unknown
19                     unknown
20                     unknown
21                     unknown
22                     unknown
23                     unknown
24                     unknown
25                     unknown
26                     unknown
27              Czech Republic
28              Czech Republic
29              Czech Republic
                 ...
1022                   unknown
1023                   Austria
1024                   Austria
1025                   unknown
1026                   unknown
1027                   Austria
1028                   unknown
1029                   unknown
1030                   Austria
1031                   Austria
1032                   unknown
1033                   unknown
1034                   Austria
1035                 Australia
1036                   unknown
1037                   unknown
1038                   unknown
1039                 Australia
1040                   unknown
1041                 Australia
1042                   unknown
1043                   unknown
1044                   unknown
1045                   unknown
1046                 Australia
1047                   unknown
1048                   unknown
1049                   unknown
1050                   unknown
1051                   unknown
Name: born_in, Length: 1052, dtype: object

In [40]:
bi_col.replace("unknown",np.nan,inplace=True) # np.nan 은  numpy에서 없는값 판다스에서는 np.nan 으로 함

In [41]:
bi_col

0                          NaN
1       Bosnia and Herzegovina
2       Bosnia and Herzegovina
3                          NaN
4                          NaN
5                          NaN
6                          NaN
7                          NaN
8                          NaN
9                          NaN
10                         NaN
11                         NaN
12                         NaN
13                         NaN
14                     Belarus
15                     Belarus
16                     Belarus
17                         NaN
18                         NaN
19                         NaN
20                         NaN
21                         NaN
22                         NaN
23                         NaN
24                         NaN
25                         NaN
26                         NaN
27              Czech Republic
28              Czech Republic
29              Czech Republic
                 ...
1022                       NaN
1023                   Austria
1024                   Austria
1025                       NaN
1026                       NaN
1027                   Austria
1028                       NaN
1029                       NaN
1030                   Austria
1031                   Austria
1032                       NaN
1033                       NaN
1034                   Austria
1035                 Australia
1036                       NaN
1037                       NaN
1038                       NaN
1039                 Australia
1040                       NaN
1041                 Australia
1042                       NaN
1043                       NaN
1044                       NaN
1045                       NaN
1046                 Australia
1047                       NaN
1048                       NaN
1049                       NaN
1050                       NaN
1051                       NaN
Name: born_in, Length: 1052, dtype: object

In [42]:
# unkown 으로 해도되는데,  drop NaN fill NaN np NaN 은 파이썬의 None하고같지만, NaN 으로 할 경우 다른기능을 쓸 수 있기때문에. 쓴다 .

In [46]:
data_dirty.columns

Index(['born_in', 'category', 'country', 'date_of_birth', 'date_of_death',
       'gender', 'link', 'place_of_birth', 'place_of_death', 'text', 'year'],
      dtype='object')

In [47]:
data_dirty = pd.read_json('data/nobel_winners_dirty.json')

describe object 또는 문자열일때 , 어제는 map 만 했는데 오늘은 apply 도 함 . 시리즈에서는 map만됨  , apply 옵션들

In [48]:
data_dirty.name = data_dirty.name.str.replace('*','') # 별표 대체

In [49]:
data_dirty.name

0                                        César Milstein
1                                           Ivo Andric
2                                      Vladimir Prelog
3                       Institut de Droit International
4                                     Auguste Beernaert
5                                   Maurice Maeterlinck
6                                     Henri La Fontaine
7                                          Jules Bordet
8                                     Corneille Heymans
9                                          Georges Pire
10                                        Albert Claude
11                                    Christian de Duve
12                                       Ilya Prigogine
13                                     François Englert
14                                       Simon Kuznets
15                                      Menachem Begin
16                                        Shimon Peres
17                                Karl Adolph Gjellerup
18                                         August Krogh
19                                           Niels Bohr
20                        Johannes Andreas Grib Fibiger
21                                           Henrik Dam
22                              Johannes Vilhelm Jensen
23                                    Ben Roy Mottelson
24                                            Aage Bohr
25                                      Niels Kaj Jerne
26                                  Jens Christian Skou
27                                  Bertha von Suttner
28                                          Gerty Cori
29                                 Carl Ferdinand Cori
                             ...
1022                                Victor Francis Hess
1023                                        Otto Loewi
1024                                      Richard Kuhn
1025                                     Wolfgang Pauli
1026                                      Max F. Perutz
1027                                   Karl von Frisch
1028                                      Konrad Lorenz
1029                                    Friedrich Hayek
1030                                       Walter Kohn
1031                                    Eric R. Kandel
1032                                   Elfriede Jelinek
1033                 International Atomic Energy Agency
1034                                    Martin Karplus
1035                            William Lawrence Bragg
1036                                  Sir Howard Florey
1037                        Sir Frank Macfarlane Burnet
1038                                  John Carew Eccles
1039                            Aleksandr M. Prokhorov
1040                                      Patrick White
1041                             John Warcup Cornforth
1042                                      John Harsanyi
1043    Peter C. Doherty  & Professor  Rolf Zinkernagel
1044                                    J. Robin Warren
1045                                     Barry Marshall
1046                            Elizabeth H. Blackburn
1047                                   Brian P. Schmidt
1048                              Carlos Saavedra Lamas
1049                                   Bernardo Houssay
1050                               Luis Federico Leloir
1051                              Adolfo Pérez Esquivel
Name: name, Length: 1052, dtype: object

-------------------
번외

In [51]:
None == False

False

근데 if 에서는 둘다 False 를 쓴다

In [52]:
np.nan == np.nan

False

#없는 애인데 메모리 값이 달라서 , 다르다고 나옴 
#None 은 없는값, np.NaN 은 활용할 수 없는값.

In [53]:
data_dirty.born_in.isnull()

0       False
1       False
2       False
3       False
4       False
5       False
6       False
7       False
8       False
9       False
10      False
11      False
12      False
13      False
14      False
15      False
16      False
17      False
18      False
19      False
20      False
21      False
22      False
23      False
24      False
25      False
26      False
27      False
28      False
29      False
        ...
1022    False
1023    False
1024    False
1025    False
1026    False
1027    False
1028    False
1029    False
1030    False
1031    False
1032    False
1033    False
1034    False
1035    False
1036    False
1037    False
1038    False
1039    False
1040    False
1041    False
1042    False
1043    False
1044    False
1045    False
1046    False
1047    False
1048    False
1049    False
1050    False
1051    False
Name: born_in, Length: 1052, dtype: bool

In [54]:
data_dirty.born_in.isna()

0       False
1       False
2       False
3       False
4       False
5       False
6       False
7       False
8       False
9       False
10      False
11      False
12      False
13      False
14      False
15      False
16      False
17      False
18      False
19      False
20      False
21      False
22      False
23      False
24      False
25      False
26      False
27      False
28      False
29      False
        ...
1022    False
1023    False
1024    False
1025    False
1026    False
1027    False
1028    False
1029    False
1030    False
1031    False
1032    False
1033    False
1034    False
1035    False
1036    False
1037    False
1038    False
1039    False
1040    False
1041    False
1042    False
1043    False
1044    False
1045    False
1046    False
1047    False
1048    False
1049    False
1050    False
1051    False
Name: born_in, Length: 1052, dtype: bool

없는값과 NaN  과 는 조금다르다

In [55]:
data_dirty[data_dirty.born_in.isnull()] # 전체에 조건을 걸어서 값이 있는 에만 보여줌

Empty DataFrame
Columns: [born_in, category, country, date_of_birth, date_of_death, gender, link, name, place_of_birth, place_of_death, text, year]
Index: []

In [56]:
# 쓸데없는거 지우는거 . 별표 지우기 , 없는값 채우는거 . 해보았다. 없는값 없에는것도 있다.
# pandas 에서 없엘때는 drop 이라는것을 쓴다 .
data_dirty.dropna() # na 값을 지우기

,born_in,category,country,date_of_birth,date_of_death,gender,link,name,place_of_birth,place_of_death,text,year
0,,Physiology or Medicine,Argentina,8 October 1927,24 March 2002,male,http://en.wikipedia.org/wiki/C%C3%A9sar_Milstein,César Milstein,"Bahía Blanca , Argentina","Cambridge , England","César Milstein , Physiology or Medicine, 1984",1984
1,Bosnia and Herzegovina,Literature,,9 October 1892,13 March 1975,male,http://en.wikipedia.org/wiki/Ivo_Andric,Ivo Andric,"Dolac (village near Travnik), Austria-Hungary ...","Belgrade, SR Serbia, SFR Yugoslavia (present-d...","Ivo Andric *, born in then Austria–Hungary ,...",1961
2,Bosnia and Herzegovina,Chemistry,,"July 23, 1906",1998-01-07,male,http://en.wikipedia.org/wiki/Vladimir_Prelog,Vladimir Prelog,"Sarajevo , Bosnia and Herzegovina , then part...","Zürich , Switzerland","Vladimir Prelog *, born in then Austria–Hung...",1975
4,,Peace,Belgium,26 July 1829,6 October 1912,male,http://en.wikipedia.org/wiki/Auguste_Marie_Fra...,Auguste Beernaert,"Ostend , Netherlands (now Belgium )","Lucerne , Switzerland","Auguste Beernaert , Peace, 1909",1909
5,,Literature,Belgium,29 August 1862,6 May 1949,male,http://en.wikipedia.org/wiki/Maurice_Maeterlinck,Maurice Maeterlinck,"Ghent , Belgium","Nice , France","Maurice Maeterlinck , Literature, 1911",1911
6,,Peace,Belgium,22 April 1854,14 May 1943,male,http://en.wikipedia.org/wiki/Henri_La_Fontaine,Henri La Fontaine,Brussels,Belgium,"Henri La Fontaine , Peace, 1913",1913
7,,Physiology or Medicine,Belgium,13 June 1870,6 April 1961,male,http://en.wikipedia.org/wiki/Jules_Bordet,Jules Bordet,"Soignies, Belgium",,"Jules Bordet , Physiology or Medicine, 1919",1919
8,,Physiology or Medicine,Belgium,28 March 1892,18 July 1968,male,http://en.wikipedia.org/wiki/Corneille_Heymans,Corneille Heymans,"Ghent , Flanders","Knokke , Flanders","Corneille Heymans , Physiology or Medicine, 1938",1938
9,,Peace,Belgium,1910-02-10,1969-01-30,male,http://en.wikipedia.org/wiki/Georges_Pire,Georges Pire,"Dinant , Belgium","Leuven , Belgium","Georges Pire , Peace, 1958",1958
10,,Physiology or Medicine,Belgium,24 August 1899,22 May 1983,male,http://en.wikipedia.org/wiki/Albert_Claude,Albert Claude,"Longlier, Neufchâteau, Belgium","Brussels , Belgium","Albert Claude , Physiology or Medicine, 1974",1974
11,,Physiology or Medicine,Belgium,2 October 1917,4 May 2013,male,http://en.wikipedia.org/wiki/Christian_de_Duve,Christian de Duve,"Thames Ditton, Surrey, United Kingdom","Grez-Doiceau, Belgium","Christian de Duve , born in the United Kingdo...",1974
12,,Chemistry,Belgium,25 January 1917,28 May 2003,male,http://en.wikipedia.org/wiki/Ilya_Prigogine,Ilya Prigogine,"Moscow , Russia","Brussels , Belgium","Ilya Prigogine , born in Russia , Chemistry, ...",1977
13,,Physics,Belgium,6 November 1932,,male,http://en.wikipedia.org/wiki/Fran%C3%A7ois_Eng...,François Englert,"Etterbeek , Brussels , Belgium",,"François Englert , Physics, 2013",2013
14,Belarus,Economics,,"April 30, 1901","July 8, 1985",male,http://en.wikipedia.org/wiki/Simon_Kuznets,Simon Kuznets,Pinsk,"Cambridge, Massachusetts","Simon Kuznets *, born in then Russian Empire,...",1971
15,Belarus,Peace,,16 August 1913,9 March 1992,male,http://en.wikipedia.org/wiki/Menachem_Begin,Menachem Begin,"Brest , Russian Empire","Tel Aviv , Israel","Menachem Begin *, born in then Russian Empire...",1978
16,Belarus,Peace,,2 August 1923,,male,http://en.wikipedia.org/wiki/Shimon_Peres,Shimon Peres,Poland,,"Shimon Peres *, born in then Poland, now Bela...",1994
17,,Literature,Denmark,"June 2, 1857","October 13, 1919",male,http://en.wikipedia.org/wiki/Karl_Adolph_Gjell...,Karl Adolph Gjellerup,"Roholte vicarage at Præstø , Denmark","Klotzsche , Germany","Karl Adolph Gjellerup , Literature, 1917",1917
18,,Physiology or Medicine,Denmark,"November 15, 1874","September 13, 1949",male,http://en.wikipedia.org/wiki/August_Krogh,August Krogh,,,"August Krogh , Physiology or Medicine, 1920",1920
19,,Physics,Denmark,7 October 1885,18 November 1962,male,http://en.wikipedia.org/wiki/Niels_Bohr,Niels Bohr,"Copenhagen, Denmark","Copenhagen, Denmark","Niels Bohr , Physics, 1922",1922
20,,Physiology or Medicine,Denmark,23 April 1867,30 January 1928,male,http://en.wikipedia.org/wiki/Johannes_Andreas_...,Johannes Andreas Grib Fibiger,Silkeborg,Copenhagen,"Johannes Andreas Grib Fibiger , Physiology or ...",1926
21,,Physiology or Medicine,Denmark,21 February 1895,17 April 1976,male,http://en.wikipedia.org/wiki/Henrik_Dam,Henrik Dam,,,"Henrik Dam , Physiology or Medicine, 1943",1943
22,,Literature,Denmark,1873-01-20,1950-11-25,male,http://en.wikipedia.org/wiki/Johannes_Vilhelm_...,Johannes Vilhelm Jensen,"Farsø, Jutland, Denmark","Østerbro, Copenhagen, Denmark","Johannes Vilhelm Jensen , Literature, 1944",1944
23,,Physics,Denmark,"July 9, 1926",,male,http://en.wikipedia.org/wiki/Ben_Roy_Mottelson,Ben Roy Mottelson,"Chicago, Illinois",,"Ben Roy Mottelson , Physics, 1975",1975
24,,Physics,Denmark,19 June 1922,8 September 2009,male,http://en.wikipedia.org/wiki/Aage_Bohr,Aage Bohr,"Copenhagen , Denmark","Copenhagen , Denmark","Aage Bohr , Physics, 1975",1975
25,,Physiology or Medicine,Denmark,"December 23, 1911","October 7, 1994",male,http://en.wikipedia.org/wiki/Niels_Kaj_Jerne,Niels Kaj Jerne,,,"Niels Kaj Jerne , Physiology or Medicine, 1984",1984
26,,Chemistry,Denmark,"October 8, 1918",,male,http://en.wikipedia.org/wiki/Jens_Christian_Skou,Jens Christian Skou,"Lemvig , Denmark",,"Jens Christian Skou , Chemistry, 1997",1997
27,Czech Republic,Peace,,"June 9, 1843","June 21, 1914",female,http://en.wikipedia.org/wiki/Bertha_von_Suttner,Bertha von Suttner,"Prague , Austrian Empire","Vienna , Austria-Hungary","Bertha von Suttner *, born in then Austrian-H...",1905
28,Czech Republic,Physiology or Medicine,,15 August 1896,26 October 1957,female,http://en.wikipedia.org/wiki/Gerty_Cori,Gerty Cori,"Prague , Austrian Empire",,"Gerty Cori *, born in then Austria-Hungary , ...",1947
29,Czech Republic,Physiology or Medicine,,"December 5, 1896","October 20, 1984",male,http://en.wikipedia.org/wiki/Carl_Ferdinand_Cori,Carl Ferdinand Cori,Prague,"Cambridge, Massachusetts","Carl Ferdinand Cori *, born in then Austria-H...",1947
30,,Chemistry,Czech Republic,"December 20, 1890","March 27, 1967",male,http://en.wikipedia.org/wiki/Jaroslav_Heyrovsk...,Jaroslav Heyrovský,"Prague , Bohemia","Cambridge , England","Jaroslav Heyrovský , Chemistry, 1959",1959
...,...,...,...,...,...,...,...,...,...,...,...,...
1021,,Physics,Austria,12 August 1887,4 January 1961,male,http://en.wikipedia.org/wiki/Erwin_Schr%C3%B6d...,Erwin Schrödinger,"Erdberg, Vienna, Austria","Vienna, Austria","Erwin Schrödinger , Physics, 1933",1933
1022,,Physics,Austria,24 June 1883,17 December 1964,male,http://en.wikipedia.org/wiki/Victor_Francis_Hess,Victor Francis Hess,"Schloss Waldstein, Peggau , Austria","Mount Vernon, New York , USA","Victor Francis Hess , Physics, 1936",1936
1023,Austria,Physiology or Medicine,,"June 3, 1873","December 25, 1961",male,http://en.wikipedia.org/wiki/Otto_Loewi,Otto Loewi,"Frankfurt , Germany","New York City , United States","Otto Loewi *, Physiology or Medicine, 1936",1936
1024,Austria,Chemistry,,"December 3, 1900","August 1, 1967",male,http://en.wikipedia.org/wiki/Richard_Kuhn,Richard Kuhn,"Vienna , Austria","Heidelberg , Germany","Richard Kuhn *, Chemistry, 1938",1938
1025,,Physics,Austria,25 April 1900,15 December 1958,male,http://en.wikipedia.org/wiki/Wolfgang_Pauli,Wolfgang Pauli,"Vienna , Austria-Hungary","Zurich , Switzerland","Wolfgang Pauli , Physics, 1945",1945
1026,,Chemistry,Austria,19 May 1914,6 February 2002,male,http://en.wikipedia.org/wiki/Max_F._Perutz,Max F. Perutz,"Vienna , Austria","Cambridge , England","Max F. Perutz , Chemistry, 1962",1962
1027,Austria,Physiology or Medicine,,1886-11-20,1982-06-12,male,http://en.wikipedia.org/wiki/Karl_von_Frisch,Karl von Frisch,"Vienna, Austria","Munich , Germany","Karl von Frisch *, Physiology or Medicine, 1973",1973
1028,,Physiology or Medicine,Austria,"November 7, 1903","February 27, 1989",male,http://en.wikipedia.org/wiki/Konrad_Lorenz,Konrad Lorenz,"Vienna, Austria","Vienna, Austria","Konrad Lorenz , Physiology or Medicine, 1973",1973
1029,,Economics,Austria,8 May 1899,23 March 1992,male,http://en.wikipedia.org/wiki/Friedrich_Hayek,Friedrich Hayek,"Vienna, Austria-Hungary","Freiburg, Germany","Friedrich Hayek , Economics, 1974",1974
1030,Austria,Chemistry,,1923-03-09,,male,http://en.wikipedia.org/wiki/Walter_Kohn,Walter Kohn,Vienna,,"Walter Kohn *, Chemistry, 1998",1998
1031,Austria,Physiology or Medicine,,7 November 1929,,male,http://en.wikipedia.org/wiki/Eric_R._Kandel,Eric R. Kandel,"Vienna , Austria",,"Eric R. Kandel *, Physiology or Medicine, 2000",2000
1032,,Literature,Austria,20 October 1946,,female,http://en.wikipedia.org/wiki/Elfriede_Jelinek,Elfriede Jelinek,"Mürzzuschlag , Styria , Austria",,"Elfriede Jelinek , Literature, 2004",2004
1034,Austria,Chemistry,,"March 15, 1930",,male,http://en.wikipedia.org/wiki/Martin_Karplus,Martin Karplus,"Vienna , Austria",,"Martin Karplus *, Chemistry, 2013",2013
1035,Australia,Physics,,31 March 1890,1 July 1971,male,http://en.wikipedia.org/wiki/William_Lawrence_...,William Lawrence Bragg,"North Adelaide , South Australia","Waldringfield , Suffolk, England","William Lawrence Bragg *, Physics, 1915",1915
1036,,Physiology or Medicine,Australia,24 September 1898,21 February 1968,male,http://en.wikipedia.org/wiki/Howard_Walter_Florey,Sir Howard Florey,"Adelaide , South Australia","Oxford , United Kingdom","Sir Howard Florey , Physiology or Medicine, 1945",1945
1037,,Physiology or Medicine,Australia,3 September 1899,31 August 1985,male,http://en.wikipedia.org/wiki/Frank_Macfarlane_...,Sir Frank Macfarlane Burnet,"Traralgon, Victoria","Port Fairy, Victoria","Sir Frank Macfarlane Burnet , Physiology or Me...",1960
1038,,Physiology or Medicine,Australia,27 January 1903,2 May 1997,male,http://en.wikipedia.org/wiki/John_Carew_Eccles,John Carew Eccles,"Melbourne , Australia","Tenero-Contra , Switzerland","John Carew Eccles , Physiology or Medicine, 1963",1963
1039,Australia,Physics,,11 July 1916,8 January 2002,male,http://en.wikipedia.org/wiki/Aleksandr_M._Prok...,Aleksandr M. Prokhorov,"Atherton, Queensland , Australia","Moscow , Russia","Aleksandr M. Prokhorov *, Physics, 1964",1964
1040,,Literature,Australia,28 May 1912,30 September 1990,male,http://en.wikipedia.org/wiki/Patrick_White,Patrick White,"Knightsbridge , London","Sydney, Australia","Patrick White , born in the United Kingdom , ...",1973
1041,Australia,Chemistry,,7 September 1917,8 December 2013,male,http://en.wikipedia.org/wiki/John_Warcup_Cornf...,John Warcup Cornforth,"Sydney , Australia",England,"John Warcup Cornforth *, Chemistry, 1975",1975
1042,,Economics,Australia,"May 29, 1920","August 9, 2000",male,http://en.wikipedia.org/wiki/John_Harsanyi,John Harsanyi,"Budapest , Hungary","Berkeley, California , USA","John Harsanyi , Economics, 1994",1994
1043,,Physiology or Medicine,Australia,15 October 1940,,male,http://en.wikipedia.org/wiki/Peter_C._Doherty,Peter C. Doherty & Professor Rolf Zinkernagel,Brisbane,,Peter C. Doherty & Professor Rolf Zinkernage...,1996
1044,,Physiology or Medicine,Australia,11 June 1937,,male,http://en.wikipedia.org/wiki/Robin_Warren,J. Robin Warren,"Adelaide , Australia",,"J. Robin Warren , Physiology or Medicine, 2005",2005
1045,,Physiology or Medicine,Australia,30 September 1951,,male,http://en.wikipedia.org/wiki/Barry_Marshall,Barry Marshall,"Kalgoorlie, Western Australia",,"Barry Marshall , Physiology or Medicine, 2005",2005
1046,Australia,Physiology or Medicine,,1948-11-26,,female,http://en.wikipedia.org/wiki/Elizabeth_H._Blac...,Elizabeth H. Blackburn,"Hobart , Tasmania , Australia",,"Elizabeth H. Blackburn *, Physiology or Medici...",2009
1047,,Physics,Australia,"February 24, 1967",,male,http://en.wikipedia.org/wiki/Brian_P._Schmidt,Brian P. Schmidt,"Missoula, Montana",,"Brian P. Schmidt , born in the United States ...",2011
1048,,Peace,Argentina,"November 1, 1878","May 5, 1959",male,http://en.wikipedia.org/wiki/Carlos_Saavedra_L...,Carlos Saavedra Lamas,"Buenos Aires , Argentina","Buenos Aires, Argentina","Carlos Saavedra Lamas , Peace, 1936",1936
1049,,Physiology or Medicine,Argentina,1887-04-10,1971-09-21,male,http://en.wikipedia.org/wiki/Bernardo_Houssay,Bernardo Houssay,"Buenos Aires , Argentina","Buenos Aires , Argentina","Bernardo Houssay , Physiology or Medicine, 1947",1947
1050,,Chemistry,Argentina,1906-9-6,1987-12-2,male,http://en.wikipedia.org/wiki/Luis_Federico_Leloir,Luis Federico Leloir,"Paris , France","Buenos Aires , Argentina","Luis Federico Leloir , Chemistry, 1970",1970
1051,,Peace,Argentina,"November 26, 1931",,male,http://en.wikipedia.org/wiki/Adolfo_P%C3%A9rez...,Adolfo Pérez Esquivel,Buenos Aires,,"Adolfo Pérez Esquivel , Peace, 1980",1980

-----------------------
중복값은 의미가없다 .중복값 처리하는게 duplicated .

In [57]:
data_dirty.duplicated('name') #중복되면 true , 없으면 false 
#data_dirty.name.duplicated() 이것도됨.

0       False
1       False
2       False
3       False
4       False
5       False
6       False
7       False
8       False
9       False
10      False
11      False
12      False
13      False
14      False
15      False
16      False
17      False
18      False
19      False
20      False
21      False
22      False
23      False
24      False
25      False
26      False
27      False
28      False
29      False
        ...
1022    False
1023    False
1024    False
1025    False
1026    False
1027    False
1028    False
1029     True
1030    False
1031    False
1032    False
1033    False
1034    False
1035    False
1036    False
1037    False
1038    False
1039    False
1040    False
1041    False
1042    False
1043    False
1044    False
1045    False
1046    False
1047     True
1048    False
1049    False
1050    False
1051    False
Length: 1052, dtype: bool

In [58]:
data_dirty[data_dirty.duplicated('name')].name #중복된 사람들 이름

131                   Aaron Klug
134               César Milstein
309             Linus C. Pauling
326                 John Bardeen
366             Baruj Benacerraf
373            Franco Modigliani
376         Rita Levi-Montalcini
405                 Ronald Coase
457              Daniel Kahneman
476                Robert Aumann
580             Frederick Sanger
586               Sydney Brenner
598               Michael Levitt
622                  Felix Bloch
630            Edmond H. Fischer
672             Wilhelm Ostwald
684             Wassily Leontief
688              Menachem Begin
709       Marie Skłodowska-Curie
712              Andrew Schally
714              Czesław Miłosz
715              Roald Hoffmann
717             Georges Charpak
718                Shimon Peres
721               Leonid Hurwicz
731                 Lars Onsager
734                 Ivar Giaever
773               Yoichiro Nambu
776              Osamu Shimomura
778              Ei-ichi Negishi
780               Shuji Nakamura
790                 Daniel Bovet
797              Michael Levitt
798                Arieh Warshel
805               Betty Williams
813                Mother Teresa
830                Avram Hershko
831               Charles K. Kao
844              Albert Einstein
905             Thomas C. Südhof
909                 Henry Dunant
919                  Marie Curie
940                Gérard Debreu
947     Médecins Sans Frontières
960                Ragnar Granit
975                Tsung-Dao Lee
976               Chen Ning Yang
985            Ernest Rutherford
995                Sidney Altman
1004             Jack W. Szostak
1006           Ralph M. Steinman
1013              Philipp Lenard
1029             Friedrich Hayek
1047            Brian P. Schmidt
Name: name, dtype: object

In [62]:
all_dupes = data_dirty[data_dirty.duplicated('name')\
|data_dirty.duplicated('name',keep='last')]
all_dupes.count()

 # \를 해도 되고 안해도된다 . 줄 바꿈인데 [] 안에 있으니까.

born_in           108
category          108
country           108
date_of_birth     106
date_of_death     106
gender            104
link              108
name              108
place_of_birth    106
place_of_death    106
text              108
year              108
dtype: int64

In [63]:
#무한대는 값이 있다 없다? , 새번쨰는 중복이 되어있냐 .되어있지않냐 , 전체로우가 똑같으면 무의미하다 . 가중치 계산해서 하지않는다 .
#컬럼을 하나 더 추가해서 하는게 일반적이다 . 
#중복값 제거하는게 큰 이슈다 
#중복이 있으면 제거해준다 .

In [64]:
data_dirty[data_dirty.duplicated()]

Empty DataFrame
Columns: [born_in, category, country, date_of_birth, date_of_death, gender, link, name, place_of_birth, place_of_death, text, year]
Index: []

## concat

# 다음주 스파크 3일할것이다.
#사이킷런 
#딥러닝

#pandas - > 기존데이터 분석하기 좋게 바꾸는거. 지금 단계에서는 cleaning  하는중임 . 
# 어떤 교수가 tidy 데이터의 원칙을 만들었다.

수집에 대한 원칙 
DB설계
tidy data

# 오후수업 시작. 

컬럼명에 절때 변수가 있으면안된다.  reshape

In [99]:
import pandas as pd
df =pd.read_csv('pew.txt',sep='\t')

In [82]:
df

,religion,<$10k,$10-20k,$20-30k,$30-40k,$40-50k,$50-75k,$75-100k,$100-150k,>150k,Don't know/refused
0,Agnostic,27,34,60,81,76,137,122,109,84,96
1,Atheist,12,27,37,52,35,70,73,59,74,76
2,Buddhist,27,21,30,34,33,58,62,39,53,54
3,Catholic,418,617,732,670,638,1116,949,792,633,1489
4,Don’t know/refused,15,14,15,11,10,35,21,17,18,116
5,Evangelical Prot,575,869,1064,982,881,1486,949,723,414,1529
6,Hindu,1,9,7,9,11,34,47,48,54,37
7,Historically Black Prot,228,244,236,238,197,223,131,81,78,339
8,Jehovah's Witness,20,27,24,24,21,30,15,11,6,37
9,Jewish,19,19,25,25,30,95,69,87,151,162
10,Mainline Prot,289,495,619,655,651,1107,939,753,634,1328
11,Mormon,29,40,48,51,56,112,85,49,42,69
12,Muslim,6,7,9,10,9,23,16,8,6,22
13,Orthodox,13,17,23,32,32,47,38,42,46,73
14,Other Christian,9,7,11,13,13,14,18,14,12,18
15,Other Faiths,20,33,40,46,49,63,46,40,41,71
16,Other World Religions,5,2,3,4,2,7,3,4,4,8
17,Unaffiliated,217,299,374,365,341,528,407,321,258,597

In [83]:
df=df.set_index('religion')

In [84]:
df =df.stack()

In [85]:
df  # melt 랑 조금 비슷하다. 
#스택은 한열로 쌋는것. 스택 그래프 .

religion
Agnostic               <$10k                  27
                       $10-20k                34
                       $20-30k                60
                       $30-40k                81
                       $40-50k                76
                       $50-75k               137
                       $75-100k              122
                       $100-150k             109
                       >150k                  84
                       Don't know/refused     96
Atheist                <$10k                  12
                       $10-20k                27
                       $20-30k                37
                       $30-40k                52
                       $40-50k                35
                       $50-75k                70
                       $75-100k               73
                       $100-150k              59
                       >150k                  74
                       Don't know/refused     76
Buddhist               <$10k                  27
                       $10-20k                21
                       $20-30k                30
                       $30-40k                34
                       $40-50k                33
                       $50-75k                58
                       $75-100k               62
                       $100-150k              39
                       >150k                  53
                       Don't know/refused     54
                                            ...
Other Faiths           <$10k                  20
                       $10-20k                33
                       $20-30k                40
                       $30-40k                46
                       $40-50k                49
                       $50-75k                63
                       $75-100k               46
                       $100-150k              40
                       >150k                  41
                       Don't know/refused     71
Other World Religions  <$10k                   5
                       $10-20k                 2
                       $20-30k                 3
                       $30-40k                 4
                       $40-50k                 2
                       $50-75k                 7
                       $75-100k                3
                       $100-150k               4
                       >150k                   4
                       Don't know/refused      8
Unaffiliated           <$10k                 217
                       $10-20k               299
                       $20-30k               374
                       $30-40k               365
                       $40-50k               341
                       $50-75k               528
                       $75-100k              407
                       $100-150k             321
                       >150k                 258
                       Don't know/refused    597
Length: 180, dtype: int64

In [86]:
df = df.unstack() #다시 되돌리기

In [87]:
df

,<$10k,$10-20k,$20-30k,$30-40k,$40-50k,$50-75k,$75-100k,$100-150k,>150k,Don't know/refused
religion,,,,,,,,,,
Agnostic,27,34,60,81,76,137,122,109,84,96
Atheist,12,27,37,52,35,70,73,59,74,76
Buddhist,27,21,30,34,33,58,62,39,53,54
Catholic,418,617,732,670,638,1116,949,792,633,1489
Don’t know/refused,15,14,15,11,10,35,21,17,18,116
Evangelical Prot,575,869,1064,982,881,1486,949,723,414,1529
Hindu,1,9,7,9,11,34,47,48,54,37
Historically Black Prot,228,244,236,238,197,223,131,81,78,339
Jehovah's Witness,20,27,24,24,21,30,15,11,6,37
Jewish,19,19,25,25,30,95,69,87,151,162
Mainline Prot,289,495,619,655,651,1107,939,753,634,1328
Mormon,29,40,48,51,56,112,85,49,42,69
Muslim,6,7,9,10,9,23,16,8,6,22
Orthodox,13,17,23,32,32,47,38,42,46,73
Other Christian,9,7,11,13,13,14,18,14,12,18
Other Faiths,20,33,40,46,49,63,46,40,41,71
Other World Religions,5,2,3,4,2,7,3,4,4,8
Unaffiliated,217,299,374,365,341,528,407,321,258,597

In [88]:
df.unstack() #또 언스택하니까 , 기준을 잘봐라  행하고 열하고 차이.

                    religion
<$10k               Agnostic                     27
                    Atheist                      12
                    Buddhist                     27
                    Catholic                    418
                    Don’t know/refused           15
                    Evangelical Prot            575
                    Hindu                         1
                    Historically Black Prot     228
                    Jehovah's Witness            20
                    Jewish                       19
                    Mainline Prot               289
                    Mormon                       29
                    Muslim                        6
                    Orthodox                     13
                    Other Christian               9
                    Other Faiths                 20
                    Other World Religions         5
                    Unaffiliated                217
$10-20k             Agnostic                     34
                    Atheist                      27
                    Buddhist                     21
                    Catholic                    617
                    Don’t know/refused           14
                    Evangelical Prot            869
                    Hindu                         9
                    Historically Black Prot     244
                    Jehovah's Witness            27
                    Jewish                       19
                    Mainline Prot               495
                    Mormon                       40
                                               ...
>150k               Hindu                        54
                    Historically Black Prot      78
                    Jehovah's Witness             6
                    Jewish                      151
                    Mainline Prot               634
                    Mormon                       42
                    Muslim                        6
                    Orthodox                     46
                    Other Christian              12
                    Other Faiths                 41
                    Other World Religions         4
                    Unaffiliated                258
Don't know/refused  Agnostic                     96
                    Atheist                      76
                    Buddhist                     54
                    Catholic                   1489
                    Don’t know/refused          116
                    Evangelical Prot           1529
                    Hindu                        37
                    Historically Black Prot     339
                    Jehovah's Witness            37
                    Jewish                      162
                    Mainline Prot              1328
                    Mormon                       69
                    Muslim                       22
                    Orthodox                     73
                    Other Christian              18
                    Other Faiths                 71
                    Other World Religions         8
                    Unaffiliated                597
Length: 180, dtype: int64

In [89]:
#스택은 행으로 쌓는거, 언스택은 열로 쌓는거. 
#한줄로 만드는거 , 시리즈다 , 언스택

In [91]:
df.index

Index(['Agnostic', 'Atheist', 'Buddhist', 'Catholic', 'Don’t know/refused',
       'Evangelical Prot', 'Hindu', 'Historically Black Prot',
       'Jehovah's Witness', 'Jewish', 'Mainline Prot', 'Mormon', 'Muslim',
       'Orthodox', 'Other Christian', 'Other Faiths', 'Other World Religions',
       'Unaffiliated'],
      dtype='object', name='religion')

In [93]:
df.index = df.index.rename('A')

In [94]:
df

,<$10k,$10-20k,$20-30k,$30-40k,$40-50k,$50-75k,$75-100k,$100-150k,>150k,Don't know/refused
A,,,,,,,,,,
Agnostic,27,34,60,81,76,137,122,109,84,96
Atheist,12,27,37,52,35,70,73,59,74,76
Buddhist,27,21,30,34,33,58,62,39,53,54
Catholic,418,617,732,670,638,1116,949,792,633,1489
Don’t know/refused,15,14,15,11,10,35,21,17,18,116
Evangelical Prot,575,869,1064,982,881,1486,949,723,414,1529
Hindu,1,9,7,9,11,34,47,48,54,37
Historically Black Prot,228,244,236,238,197,223,131,81,78,339
Jehovah's Witness,20,27,24,24,21,30,15,11,6,37
Jewish,19,19,25,25,30,95,69,87,151,162
Mainline Prot,289,495,619,655,651,1107,939,753,634,1328
Mormon,29,40,48,51,56,112,85,49,42,69
Muslim,6,7,9,10,9,23,16,8,6,22
Orthodox,13,17,23,32,32,47,38,42,46,73
Other Christian,9,7,11,13,13,14,18,14,12,18
Other Faiths,20,33,40,46,49,63,46,40,41,71
Other World Religions,5,2,3,4,2,7,3,4,4,8
Unaffiliated,217,299,374,365,341,528,407,321,258,597

In [95]:
df.rename() # 차이는 데이터프레임의 rename . 인자의 mapper 은 dict 다 .

TypeError: must pass an index to rename

In [103]:
df.set_index('religion')

,<$10k,$10-20k,$20-30k,$30-40k,$40-50k,$50-75k,$75-100k,$100-150k,>150k,Don't know/refused
religion,,,,,,,,,,
Agnostic,27,34,60,81,76,137,122,109,84,96
Atheist,12,27,37,52,35,70,73,59,74,76
Buddhist,27,21,30,34,33,58,62,39,53,54
Catholic,418,617,732,670,638,1116,949,792,633,1489
Don’t know/refused,15,14,15,11,10,35,21,17,18,116
Evangelical Prot,575,869,1064,982,881,1486,949,723,414,1529
Hindu,1,9,7,9,11,34,47,48,54,37
Historically Black Prot,228,244,236,238,197,223,131,81,78,339
Jehovah's Witness,20,27,24,24,21,30,15,11,6,37
Jewish,19,19,25,25,30,95,69,87,151,162
Mainline Prot,289,495,619,655,651,1107,939,753,634,1328
Mormon,29,40,48,51,56,112,85,49,42,69
Muslim,6,7,9,10,9,23,16,8,6,22
Orthodox,13,17,23,32,32,47,38,42,46,73
Other Christian,9,7,11,13,13,14,18,14,12,18
Other Faiths,20,33,40,46,49,63,46,40,41,71
Other World Religions,5,2,3,4,2,7,3,4,4,8
Unaffiliated,217,299,374,365,341,528,407,321,258,597

In [106]:
a = df['<$10k']

In [107]:
a

0      27
1      12
2      27
3     418
4      15
5     575
6       1
7     228
8      20
9      19
10    289
11     29
12      6
13     13
14      9
15     20
16      5
17    217
Name: <$10k, dtype: int64

In [ ]:
a.rename('BBBB')

In [109]:
data_dirty = pd.read_json('data/nobel_winners_dirty.json')

In [110]:
data_dirty.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1052 entries, 0 to 1051
Data columns (total 12 columns):
born_in           1052 non-null object
category          1052 non-null object
country           1052 non-null object
date_of_birth     1044 non-null object
date_of_death     1044 non-null object
gender            1040 non-null object
link              1052 non-null object
name              1052 non-null object
place_of_birth    1044 non-null object
place_of_death    1044 non-null object
text              1052 non-null object
year              1052 non-null int64
dtypes: int64(1), object(11)
memory usage: 98.7+ KB

In [111]:
data_dirty.describe()

              year
count  1052.000000
mean   1968.729087
std      33.155829
min    1809.000000
25%    1947.000000
50%    1975.000000
75%    1996.000000
max    2014.000000

In [112]:
# 기본적인 통계치보고 , aggregation 보고 , 가장 간단한 분석. 초보수준.

In [113]:
# explanatory data analasys  이건 그래프 까지 보여주는것 . EDA 다음 Seaborn